<?php

$contactUrl = '/para-empresas/contato';

$package = static fn (
    string $name,
    string $bestFor,
    string $includes,
    string $price,
    ?string $limit = null,
    ?string $estimatedTime = null,
): array => array_filter([
    'name' => $name,
    'best_for' => $bestFor,
    'includes' => $includes,
    'limit' => $limit,
    'estimated_time' => $estimatedTime,
    'price' => $price,
], static fn ($value): bool => $value !== null);

return [
    'slug' => 'desenvolvimento-de-software',
    'title' => 'Desenvolvimento de Software',
    'subtitle' => 'Sites, sistemas, automações e soluções digitais sob medida.',
    'description' => 'Criamos soluções digitais para organizar processos, substituir planilhas, melhorar a presença online e reduzir retrabalho na rotina da empresa.',
    'image' => 'img/sophdata/services/business/sites-e-sistemas-hero.webp',
    'image_alt' => 'Desenvolvimento de sites, sistemas e automações para empresas',
    'route' => '/para-empresas/desenvolvimento-de-software',
    'seo' => [
        'title' => 'Desenvolvimento de Software para Empresas | SophData',
        'description' => 'Sites, sistemas, automações, integrações e sustentação para empresas que precisam organizar processos, substituir planilhas e reduzir retrabalho.',
        'canonical' => '/para-empresas/desenvolvimento-de-software',
        'og_image' => 'img/sophdata/services/business/sites-e-sistemas-hero.webp',
        'robots' => 'index, follow',
    ],

    'cta' => [
        'label' => 'Solicitar diagnóstico digital',
        'url' => $contactUrl,
        'whatsapp_message' => 'Olá! Quero solicitar um diagnóstico digital para minha empresa com a SophData.',
    ],

    'pains' => [
        'Empresa sem site profissional',
        'Site antigo ou difícil de atualizar',
        'Processos controlados por planilhas',
        'Retrabalho e digitação repetitiva',
        'Sistema sem suporte ou desatualizado',
        'Falta de relatórios claros',
        'Dificuldade para publicar ou manter sistemas',
    ],

    'positioning' => [
        [
            'title' => 'Software com foco em rotina real',
            'description' => 'Antes de falar em tecnologia, entendemos o problema, o processo e o resultado que a empresa precisa alcançar.',
        ],
        [
            'title' => 'Presença digital com clareza',
            'description' => 'Sites, portais e landing pages ajudam a apresentar serviços, gerar confiança e captar contatos com mais organização.',
        ],
        [
            'title' => 'Sistemas para reduzir retrabalho',
            'description' => 'Soluções sob medida substituem controles manuais, centralizam informações e melhoram a tomada de decisão.',
        ],
        [
            'title' => 'Continuidade depois da entrega',
            'description' => 'Deploy, hospedagem, manutenção e evolução mantêm a solução funcionando conforme a empresa cresce.',
        ],
    ],

    'categories' => [
        [
            'slug' => 'diagnostico-e-discovery',
            'title' => 'Diagnóstico e Discovery',
            'subtitle' => 'Clareza antes de desenvolver.',
            'description' => 'Antes de criar um site, sistema ou automação, a SophData ajuda a entender a real necessidade da empresa, organizar prioridades e transformar ideias soltas em um plano de solução.',
            'image' => 'img/sophdata/services/business/sites-e-sistemas-hero.webp',
            'image_alt' => 'Diagnóstico digital para planejar sites, sistemas e automações',
            'route' => '/para-empresas/desenvolvimento-de-software/diagnostico-e-discovery',
            'cta' => [
                'label' => 'Solicitar diagnóstico digital',
                'url' => $contactUrl,
                'whatsapp_message' => 'Olá! Quero solicitar um diagnóstico digital para entender a melhor solução para minha empresa.',
            ],
            'pains' => [
                'Não saber se precisa de site, sistema ou automação',
                'Ideia de sistema sem escopo definido',
                'Processos confusos antes do desenvolvimento',
                'Risco de contratar algo maior do que o necessário',
                'Dificuldade de organizar prioridades',
                'Falta de clareza sobre prazo, escopo e investimento',
            ],
            'services' => [
                'Diagnóstico digital',
                'Discovery de produto',
                'Organização de requisitos',
                'Mapeamento de módulos',
                'Protótipo navegável',
                'Roadmap de produto',
            ],
            'packages' => [
                $package('Diagnóstico Digital Express', 'Microempresa, igreja ou pequeno negócio', 'Reunião de 1h + recomendação por e-mail', 'R$ 300', null, '1 dia'),
                $package('Diagnóstico Comercial Digital', 'Empresa sem presença digital clara', 'Análise de site, WhatsApp, jornada e oportunidades', 'R$ 600', null, '2 dias'),
                $package('Discovery de Sistema', 'Sistema sob medida', 'Requisitos, mapa de módulos e escopo inicial', 'R$ 1.500', null, '3 a 5 dias'),
                $package('Protótipo Navegável', 'Aprovar telas antes do código', 'Fluxos principais em baixa ou média fidelidade', 'R$ 2.500', null, '5 a 10 dias'),
                $package('Documento Técnico de Projeto', 'Projeto com regras e integrações', 'Escopo, critérios de aceite e arquitetura base', 'R$ 3.000', null, '5 a 10 dias'),
                $package('Roadmap de Produto', 'Plataforma em fases', 'MVP, fase 2, fase 3 e estimativa de evolução', 'R$ 2.000', null, '5 dias'),
            ],
            'scope_limits' => [
                'Não inclui desenvolvimento da solução final.',
                'Não substitui contrato de implantação ou sustentação.',
                'Escopos maiores podem exigir discovery complementar.',
            ],
            'commercial_notes' => [
                'O diagnóstico ajuda a reduzir risco antes do investimento principal.',
                'Pode ser abatido parcialmente em proposta futura, quando combinado previamente.',
            ],
        ],
        [
            'slug' => 'sites-e-portais',
            'title' => 'Sites e Portais',
            'subtitle' => 'Presença digital profissional para empresas e organizações.',
            'description' => 'Criamos páginas, sites institucionais e portais de conteúdo para apresentar serviços, gerar confiança, captar contatos e fortalecer a presença digital da empresa.',
            'image' => 'img/sophdata/services/business/sites-e-sistemas.webp',
            'image_alt' => 'Sites e portais empresariais para presença digital profissional',
            'route' => '/para-empresas/desenvolvimento-de-software/sites-e-portais',
            'cta' => [
                'label' => 'Criar meu site profissional',
                'url' => $contactUrl,
                'whatsapp_message' => 'Olá! Quero criar ou modernizar o site da minha empresa com a SophData.',
            ],
            'pains' => [
                'Empresa sem site profissional',
                'Site antigo ou desatualizado',
                'Falta de presença digital clara',
                'Dificuldade para apresentar serviços',
                'Pouca geração de contatos pelo digital',
                'Conteúdo institucional espalhado ou mal organizado',
            ],
            'services' => [
                'Landing pages',
                'Páginas comerciais',
                'Sites institucionais',
                'Portais de conteúdo',
                'Blog simples',
                'SEO técnico básico',
            ],
            'packages' => [
                $package('Landing Starter', 'Evento, campanha ou serviço único', '1 página, WhatsApp, formulário simples e responsividade', 'R$ 1.500', 'Até 5 seções'),
                $package('Landing Business', 'Produto, curso ou captação de leads', 'Copy básica, design personalizado, CTA e SEO básico', 'R$ 2.800', 'Até 8 seções'),
                $package('Landing Professional', 'Campanha com maior conversão', 'Estrutura estratégica, formulário, pixels e otimização inicial', 'R$ 4.500', 'Até 10 seções'),
                $package('Página Comercial Essencial', 'Profissional liberal ou pequena empresa', 'Home, serviços, sobre e contato em uma estrutura enxuta', 'R$ 3.000', 'Até 3 páginas ou seções'),
                $package('Site Institucional Starter', 'Empresa que precisa aparecer online', 'Home, sobre, serviços, contato e WhatsApp', 'R$ 4.000', 'Até 5 páginas'),
                $package('Site Institucional Business', 'Empresa com portfólio e autoridade', 'Páginas internas, FAQ, SEO básico e conteúdo organizado', 'R$ 7.500', 'Até 10 páginas'),
                $package('Site Institucional Professional', 'Empresa, escola ou igreja com conteúdo amplo', 'Estrutura completa, blog simples, performance e melhorias de UX', 'R$ 12.000', 'Até 15 páginas'),
                $package('Portal de Conteúdo Starter', 'Blog, ministério ou projeto educacional', 'Categorias, posts, busca simples e layout responsivo', 'R$ 8.000', 'Até 5 categorias'),
            ],
            'maintenance_plans' => [
                $package('Site Care Essencial', 'Site institucional simples', 'Backup, atualização de conteúdo leve e verificação mensal', 'R$ 300/mês', 'Até 1h por mês'),
                $package('Site Care Profissional', 'Site com páginas e campanhas', 'Backup, ajustes, segurança básica e pequenas melhorias', 'R$ 600/mês', 'Até 3h por mês'),
                $package('Site Care Gerenciado', 'Site estratégico ou com maior volume', 'Relatório, SEO técnico básico, melhorias e suporte prioritário', 'R$ 1.000/mês', 'Até 6h por mês'),
                $package('Site Care Campanhas', 'Empresa com landing pages frequentes', 'Manutenção + 1 nova landing simplificada por mês', 'R$ 1.500/mês', 'Até 8h por mês'),
            ],
            'scope_limits' => [
                'Conteúdo, fotos e identidade visual não estão inclusos por padrão.',
                'Recursos personalizados podem exigir proposta adicional.',
            ],
            'commercial_notes' => [
                'Sites podem ser combinados com manutenção mensal para manter conteúdo, segurança e melhorias em dia.',
            ],
        ],
        [
            'slug' => 'lojas-e-catalogos-digitais',
            'title' => 'Lojas e Catálogos Digitais',
            'subtitle' => 'Vitrine digital, catálogo com WhatsApp ou venda online.',
            'description' => 'Nem toda empresa precisa começar com um e-commerce completo. A SophData ajuda a escolher entre catálogo digital, loja simples ou operação de venda online mais estruturada.',
            'image' => 'img/sophdata/services/business/sites-e-sistemas.webp',
            'image_alt' => 'Catálogos digitais e lojas online para empresas',
            'route' => '/para-empresas/desenvolvimento-de-software/lojas-e-catalogos-digitais',
            'cta' => [
                'label' => 'Criar meu catálogo digital',
                'url' => $contactUrl,
                'whatsapp_message' => 'Olá! Quero avaliar um catálogo digital ou loja virtual para minha empresa.',
            ],
            'pains' => [
                'Produtos divulgados apenas por mensagem ou fotos soltas',
                'Falta de catálogo organizado',
                'Dificuldade para receber pedidos',
                'Comércio local sem presença digital de vendas',
                'Necessidade de validar venda online antes de investir alto',
            ],
            'services' => [
                'Catálogo digital',
                'Catálogo com WhatsApp',
                'Loja virtual simples',
                'E-commerce com pagamento e frete',
                'Portal de vendas sob medida',
            ],
            'packages' => [
                $package('Catálogo Digital Starter', 'Loja pequena sem venda online', 'Produtos, categorias e botão de WhatsApp', 'R$ 3.500', 'Até 30 produtos'),
                $package('Catálogo Digital Business', 'Loja com portfólio maior', 'Filtros simples, categorias e página de produto', 'R$ 6.000', 'Até 100 produtos'),
                $package('E-commerce Starter', 'Comércio local validando venda online', 'Catálogo, carrinho, checkout e integração básica', 'R$ 7.000', 'Até 50 produtos'),
                $package('E-commerce Business', 'Loja com operação recorrente', 'Pagamento, frete, cupom, painel e relatórios básicos', 'R$ 15.000', 'Até 200 produtos'),
                $package('E-commerce Professional', 'Operação com regras específicas', 'Integrações, área do cliente, estoque e recursos avançados', 'R$ 25.000', 'Até 500 produtos'),
                $package('Marketplace ou Portal de Vendas', 'Projeto com múltiplos vendedores ou regras complexas', 'Arquitetura, perfis, integrações e módulos específicos', 'A partir de R$ 60.000', 'Sob diagnóstico'),
            ],
            'scope_limits' => [
                'Meios de pagamento, frete e APIs de terceiros dependem das regras dos fornecedores.',
                'Cadastro de produtos em massa pode exigir contratação adicional.',
            ],
            'commercial_notes' => [
                'Catálogo digital pode ser uma etapa segura antes de investir em e-commerce completo.',
            ],
        ],
        [
            'slug' => 'sistemas-sob-medida',
            'title' => 'Sistemas Sob Medida',
            'subtitle' => 'Soluções web para organizar processos e substituir planilhas.',
            'description' => 'Criamos sistemas administrativos e plataformas sob medida para empresas que precisam controlar informações, padronizar rotinas, reduzir retrabalho e gerar relatórios com mais clareza.',
            'image' => 'img/sophdata/services/business/sites-e-sistemas-hero.webp',
            'image_alt' => 'Sistemas sob medida para organizar processos empresariais',
            'route' => '/para-empresas/desenvolvimento-de-software/sistemas-sob-medida',
            'cta' => [
                'label' => 'Mapear meu sistema',
                'url' => $contactUrl,
                'whatsapp_message' => 'Olá! Quero mapear um sistema sob medida para minha empresa.',
            ],
            'pains' => [
                'Planilhas demais',
                'Dados espalhados',
                'Falta de controle por usuário',
                'Processos manuais',
                'Retrabalho entre setores',
                'Falta de relatórios',
                'Sistema antigo ou sem suporte',
                'Necessidade de plataforma própria',
            ],
            'services' => [
                'Sistemas administrativos',
                'Plataformas sob medida',
                'Dashboards e relatórios',
                'Permissões por perfil',
                'Integrações leves',
                'Importação e exportação de dados',
            ],
            'packages' => [
                $package('Sistema Cadastro Essencial', 'Empresa que usa planilhas simples', 'Login, cadastros básicos e listagens', 'R$ 5.000', 'Até 3 cadastros'),
                $package('Sistema MVP Starter', 'Validar uma ideia com baixo escopo', 'Login, painel, 1 fluxo principal e relatórios simples', 'R$ 12.000', '1 perfil de usuário'),
                $package('Sistema MVP Business', 'Operação pequena com processo definido', 'Cadastros, permissões simples, dashboard e exportação', 'R$ 25.000', 'Até 5 módulos'),
                $package('Sistema Profissional', 'Empresa com regras internas próprias', 'Módulos, permissões, relatórios e integrações leves', 'R$ 50.000', 'Até 10 módulos'),
                $package('Sistema Gerencial Completo', 'Escola, igreja, clínica ou imobiliária', 'Múltiplos perfis, dashboards, relatórios e automações', 'R$ 90.000', 'Até 15 módulos'),
                $package('Plataforma Sob Medida', 'Produto digital ou operação crítica', 'Arquitetura robusta, integrações e evolução por fases', 'A partir de R$ 150.000', 'Sob diagnóstico'),
            ],
            'additional_modules' => [
                $package('Controle de usuários e perfis', 'Sistema com equipe interna', 'Permissões por função', 'R$ 2.000'),
                $package('Dashboard gerencial', 'Gestores precisam de visão rápida', 'Cards, gráficos e indicadores', 'R$ 2.500'),
                $package('Relatórios avançados', 'Gestão precisa filtrar e exportar', 'PDF, Excel e filtros', 'R$ 2.500'),
                $package('Importação de planilhas', 'Cliente tem base antiga', 'Importador CSV/XLSX com validação', 'R$ 1.800'),
                $package('Exportação de dados', 'Rotinas administrativas', 'CSV, Excel ou PDF', 'R$ 1.200'),
                $package('Notificações por e-mail', 'Avisos e confirmações', 'Templates e disparos transacionais', 'R$ 1.500'),
                $package('Integração WhatsApp', 'Atendimento e avisos', 'Link, templates ou API conforme provedor', 'R$ 2.500'),
                $package('Integração pagamento', 'Cobranças e inscrições', 'Gateway, status e retorno', 'R$ 4.000'),
                $package('API externa', 'Troca de dados com outros sistemas', 'Endpoints, autenticação e documentação', 'R$ 5.000'),
                $package('Trilha de auditoria', 'Sistemas com dados sensíveis', 'Registro de ações dos usuários', 'R$ 3.500'),
                $package('Multiempresa ou multitenancy', 'Sistema para várias unidades ou clientes', 'Separação de dados por organização', 'R$ 8.000'),
            ],
            'scope_limits' => [
                'Todo sistema sob medida precisa de diagnóstico ou discovery antes da proposta final.',
                'Escopos com muitas regras devem ser divididos em fases.',
            ],
            'commercial_notes' => [
                'Valores podem variar conforme regras, integrações, volume de dados e necessidade de suporte.',
            ],
        ],
        [
            'slug' => 'sistemas-por-segmento',
            'title' => 'Sistemas por Segmento',
            'subtitle' => 'Soluções pensadas para a realidade de cada operação.',
            'description' => 'Alguns clientes entendem melhor a solução quando enxergam seu próprio segmento. A SophData organiza sistemas por tipo de operação para facilitar o diagnóstico e a proposta.',
            'image' => 'img/sophdata/services/business/sites-e-sistemas-hero.webp',
            'image_alt' => 'Sistemas empresariais por segmento e tipo de operação',
            'route' => '/para-empresas/desenvolvimento-de-software/sistemas-por-segmento',
            'cta' => [
                'label' => 'Ver solução para meu segmento',
                'url' => $contactUrl,
                'whatsapp_message' => 'Olá! Quero avaliar uma solução de sistema para o meu segmento.',
            ],
            'pains' => [
                'Rotina específica sem sistema adequado',
                'Processos do segmento controlados por planilha',
                'Dificuldade para acompanhar cadastros, eventos, alunos, clientes ou serviços',
            ],
            'services' => [
                'Sistemas para igrejas',
                'Sistemas para escolas e cursos',
                'Sistemas para treinamentos',
                'Sistemas para clínicas',
                'Sistemas para imobiliárias',
                'Sistemas para prestadores de serviço',
                'Sistemas para ONGs e associações',
            ],
            'segments' => [
                ['name' => 'Igrejas', 'solution' => 'Sistema de membros e eventos', 'includes' => 'Membros, células/grupos, eventos, inscrições e relatórios', 'starting_price' => 'R$ 18.000', 'suggested_maintenance' => 'R$ 900/mês'],
                ['name' => 'Escolas e cursos', 'solution' => 'Sistema de alunos e turmas', 'includes' => 'Alunos, turmas, presença, comunicados e relatórios', 'starting_price' => 'R$ 25.000', 'suggested_maintenance' => 'R$ 1.200/mês'],
                ['name' => 'Treinamentos', 'solution' => 'Sistema de inscrições e certificados', 'includes' => 'Inscrições, presença, certificados e exportações', 'starting_price' => 'R$ 15.000', 'suggested_maintenance' => 'R$ 700/mês'],
                ['name' => 'Clínicas', 'solution' => 'Sistema administrativo simples', 'includes' => 'Cadastro, agenda, atendimentos e relatórios', 'starting_price' => 'R$ 22.000', 'suggested_maintenance' => 'R$ 1.000/mês'],
                ['name' => 'Imobiliárias', 'solution' => 'Sistema de imóveis e clientes', 'includes' => 'Imóveis, fotos, clientes, atendimentos e status', 'starting_price' => 'R$ 30.000', 'suggested_maintenance' => 'R$ 1.500/mês'],
                ['name' => 'Prestadores de serviço', 'solution' => 'Sistema de ordens de serviço', 'includes' => 'Clientes, chamados, orçamento, execução e histórico', 'starting_price' => 'R$ 18.000', 'suggested_maintenance' => 'R$ 900/mês'],
                ['name' => 'ONGs e Associações', 'solution' => 'Sistema de voluntários e inscrições', 'includes' => 'Cadastros, eventos, presença, relatórios e comunicação', 'starting_price' => 'R$ 16.000', 'suggested_maintenance' => 'R$ 800/mês'],
            ],
            'packages' => [],
            'scope_limits' => [
                'Cada segmento precisa de diagnóstico para validar regras e prioridades.',
            ],
            'commercial_notes' => [
                'Os segmentos servem como ponto de partida comercial, não como pacote fechado obrigatório.',
            ],
        ],
        [
            'slug' => 'portais-area-logada-pwa',
            'title' => 'Portais, Área Logada e PWA',
            'subtitle' => 'Acesso restrito, painel do cliente e experiência mobile sem complicação.',
            'description' => 'Criamos áreas logadas, portais de cliente e aplicações web instaláveis para empresas que precisam entregar conteúdo, documentos, histórico ou serviços em ambiente restrito.',
            'image' => 'img/sophdata/services/business/sites-e-sistemas-hero.webp',
            'image_alt' => 'Portais empresariais com área logada e aplicação web',
            'route' => '/para-empresas/desenvolvimento-de-software/portais-area-logada-pwa',
            'cta' => [
                'label' => 'Criar área logada',
                'url' => $contactUrl,
                'whatsapp_message' => 'Olá! Quero avaliar uma área logada, portal ou PWA para minha empresa.',
            ],
            'pains' => [
                'Clientes sem acesso organizado a documentos ou histórico',
                'Conteúdo restrito enviado manualmente',
                'Equipe externa sem painel simples de operação',
                'Necessidade de experiência mobile sem app nativo imediato',
            ],
            'services' => [
                'Área logada',
                'Portal do cliente',
                'Portal de membros ou alunos',
                'PWA',
                'Aplicativo híbrido sob diagnóstico',
            ],
            'packages' => [
                $package('Área Logada Starter', 'Site com clientes, alunos ou membros', 'Login, painel simples e conteúdo restrito', 'R$ 8.000', '1 perfil'),
                $package('Portal do Cliente', 'Empresas de serviço', 'Login, chamados, documentos e histórico', 'R$ 18.000', 'Até 3 fluxos'),
                $package('PWA Starter', 'Acesso mobile sem app store', 'Web app responsivo, instalável e com navegação otimizada', 'R$ 15.000', '1 fluxo principal'),
                $package('PWA Business', 'Operação com equipe externa', 'Login, painel, notificações web e offline limitado', 'R$ 35.000', 'Até 5 módulos'),
                $package('Aplicativo Híbrido', 'Projeto mobile específico', 'App Android/iOS com backend e publicação', 'A partir de R$ 60.000', 'Sob diagnóstico'),
            ],
            'scope_limits' => [
                'Publicação em lojas de aplicativo depende das regras das plataformas.',
                'Recursos offline avançados precisam de avaliação técnica específica.',
            ],
            'commercial_notes' => [
                'PWA pode ser uma alternativa inicial mais simples que aplicativo nativo.',
            ],
        ],
        [
            'slug' => 'automacoes-e-integracoes',
            'title' => 'Automações e Integrações',
            'subtitle' => 'Menos retrabalho e mais conexão entre ferramentas.',
            'description' => 'Automatizamos tarefas repetitivas, conectamos ferramentas e criamos integrações para reduzir digitação manual, melhorar relatórios e acelerar rotinas administrativas.',
            'image' => 'img/sophdata/services/business/automacao-e-dados.webp',
            'image_alt' => 'Automações e integrações para reduzir retrabalho empresarial',
            'route' => '/para-empresas/desenvolvimento-de-software/automacoes-e-integracoes',
            'cta' => [
                'label' => 'Automatizar meu processo',
                'url' => $contactUrl,
                'whatsapp_message' => 'Olá! Quero automatizar processos ou integrar ferramentas na minha empresa.',
            ],
            'pains' => [
                'Digitação repetitiva',
                'Informações duplicadas em várias ferramentas',
                'Falta de painel ou relatório',
                'Documentos gerados manualmente',
                'Processos simples que consomem muito tempo',
                'Sistemas que não conversam entre si',
            ],
            'services' => [
                'Formulários inteligentes',
                'Dashboards simples',
                'Automação de documentos',
                'Integrações com planilhas',
                'Integrações com APIs',
                'Rotinas de limpeza e migração de dados',
            ],
            'packages' => [
                $package('Formulário inteligente', 'Captura de contatos e inscrições', 'Formulário, validação e armazenamento', 'R$ 1.200'),
                $package('Dashboard simples', 'Gestão rápida', 'Indicadores e gráficos básicos', 'R$ 2.500'),
                $package('Automação de documentos', 'Recibos, certificados ou contratos', 'Modelo + preenchimento automatizado', 'R$ 2.500'),
                $package('Integração Google Sheets', 'Processos leves', 'Envio ou consulta em planilhas', 'R$ 1.800'),
                $package('Integração Google Workspace', 'Agenda, drive, formulários ou e-mail', 'Fluxo conectado com ferramentas Google', 'R$ 3.000'),
                $package('Integração API simples', 'Um sistema externo', 'Consumo ou envio de dados', 'R$ 4.000'),
                $package('Integração API profissional', 'Fluxo crítico ou autenticação complexa', 'Sincronização, logs e tratamento de falhas', 'R$ 8.000'),
                $package('Rotina ETL simples', 'Limpeza e migração de dados', 'Extração, transformação e carga', 'R$ 3.500'),
                $package('Robô administrativo simples', 'Tarefa repetitiva', 'Script automatizado documentado', 'R$ 2.500'),
            ],
            'scope_limits' => [
                'Integrações dependem de permissão, API e estabilidade do fornecedor externo.',
                'Automações críticas exigem logs, monitoramento e plano de contingência.',
            ],
            'commercial_notes' => [
                'Automações devem começar por tarefas repetitivas de alto impacto na rotina.',
            ],
        ],
        [
            'slug' => 'deploy-hospedagem',
            'title' => 'Deploy e Hospedagem',
            'subtitle' => 'Publicação e ambiente organizado para sites e sistemas.',
            'description' => 'Publicamos sites e sistemas em ambientes configurados, com domínio, SSL, banco de dados, backup e cuidados técnicos para manter a solução em operação.',
            'image' => 'img/sophdata/services/business/automacao-e-dados-hero.webp',
            'image_alt' => 'Deploy e hospedagem para manter sites e sistemas em operação',
            'route' => '/para-empresas/desenvolvimento-de-software/deploy-hospedagem',
            'cta' => [
                'label' => 'Publicar meu sistema',
                'url' => $contactUrl,
                'whatsapp_message' => 'Olá! Quero publicar ou organizar o ambiente de um site ou sistema.',
            ],
            'pains' => [
                'Site pronto mas fora do ar',
                'Sistema sem ambiente organizado',
                'Dificuldade com domínio, SSL, banco e DNS',
                'Hospedagem sem backup ou rotina de verificação',
            ],
            'services' => [
                'Publicação de sites',
                'Deploy de sistemas PHP/Laravel',
                'Configuração de VPS',
                'Banco de dados',
                'Migração de hospedagem',
                'Ambiente de homologação',
                'Deploy automatizado simples',
            ],
            'packages' => [
                $package('Publicação de site simples', 'Site estático ou institucional', 'Domínio, hospedagem, SSL e publicação', 'R$ 300'),
                $package('Deploy Laravel/PHP compartilhado', 'Sistema em hospedagem comum', 'Build, upload, banco e .env', 'R$ 700'),
                $package('Deploy Laravel em VPS', 'Sistema com maior controle', 'Linux, Nginx/Apache, PHP, banco e SSL', 'R$ 1.500'),
                $package('Configuração de banco MySQL/PostgreSQL', 'Usuários, permissões e backup inicial', 'Banco configurado e acesso organizado', 'R$ 600'),
                $package('Migração de hospedagem', 'Troca de provedor', 'Arquivos, banco, DNS e testes', 'R$ 900'),
                $package('Ambiente de homologação', 'Projetos com testes antes de produção', 'Ambiente separado para validação', 'R$ 1.200'),
                $package('Deploy automatizado simples', 'Projeto com Git', 'Script ou pipeline básico', 'R$ 1.500'),
            ],
            'managed_environment_plans' => [
                $package('Ambiente Essencial', 'Site institucional', 'Verificação, SSL e backup básico', 'R$ 150/mês', '1 site'),
                $package('Ambiente Profissional', 'Site + landing pages', 'Backup, atualizações e suporte de ambiente', 'R$ 300/mês', 'Até 3 sites'),
                $package('Ambiente Sistema', 'Laravel/PHP com banco', 'Backup, logs, SSL e revisão mensal', 'R$ 500/mês', '1 sistema'),
                $package('Ambiente Gerenciado', 'Sistema crítico pequeno', 'Monitoramento básico, backup e suporte prioritário', 'R$ 900/mês', '1 sistema + homologação'),
            ],
            'scope_limits' => [
                'Custos de provedor, domínio, servidor e serviços externos são cobrados a parte.',
                'Ambientes críticos exigem plano de suporte e backup adequado.',
            ],
            'commercial_notes' => [
                'Deploy bem organizado reduz risco de falhas depois da entrega.',
            ],
        ],
        [
            'slug' => 'sustentacao-e-evolucao',
            'title' => 'Sustentação e Evolução',
            'subtitle' => 'Software não deve ser entregue e esquecido.',
            'description' => 'Mantemos sites e sistemas em operação, corrigindo falhas, acompanhando atualizações e planejando melhorias para que a solução continue útil conforme a empresa evolui.',
            'image' => 'img/sophdata/services/business/automacao-e-dados-hero.webp',
            'image_alt' => 'Sustentação e evolução contínua de sites e sistemas empresariais',
            'route' => '/para-empresas/desenvolvimento-de-software/sustentacao-e-evolucao',
            'cta' => [
                'label' => 'Manter meu sistema',
                'url' => $contactUrl,
                'whatsapp_message' => 'Olá! Quero contratar sustentação ou evolução para um site ou sistema.',
            ],
            'pains' => [
                'Sistema entregue sem suporte',
                'Falhas pequenas acumulando na rotina',
                'Necessidade de melhorias frequentes',
                'Atualizações técnicas sem acompanhamento',
                'Empresa dependente de software sem plano de continuidade',
            ],
            'services' => [
                'Sustentação mensal',
                'Correções leves',
                'Pequenas melhorias',
                'Banco de horas',
                'Planejamento de evolução',
                'Acompanhamento técnico',
            ],
            'packages' => [
                $package('Sustentação Essencial', 'Site ou sistema simples', 'Correções leves, orientação e atualização técnica', 'R$ 700/mês', 'Até 3h por mês'),
                $package('Sustentação Profissional', 'Sistema em uso recorrente', 'Correções, pequenos ajustes, backup e suporte', 'R$ 1.500/mês', 'Até 8h por mês'),
                $package('Sustentação Gerenciada', 'Empresa dependente do sistema', 'Prioridade, relatórios, melhorias e monitoramento básico', 'R$ 3.000/mês', 'Até 16h por mês'),
                $package('Sustentação Crítica', 'Operação sensível', 'Acompanhamento próximo, planejamento e prioridade ampliada', 'R$ 5.000/mês', 'Até 30h por mês'),
            ],
            'hour_banks' => [
                ['name' => 'Horas 5', 'hours_per_month' => '5h', 'recommended_use' => 'Ajustes pequenos e suporte leve', 'effective_hourly_rate' => 'R$ 160/h', 'price' => 'R$ 800/mês'],
                ['name' => 'Horas 10', 'hours_per_month' => '10h', 'recommended_use' => 'Melhorias frequentes', 'effective_hourly_rate' => 'R$ 150/h', 'price' => 'R$ 1.500/mês'],
                ['name' => 'Horas 20', 'hours_per_month' => '20h', 'recommended_use' => 'Evolução contínua moderada', 'effective_hourly_rate' => 'R$ 140/h', 'price' => 'R$ 2.800/mês'],
                ['name' => 'Horas 40', 'hours_per_month' => '40h', 'recommended_use' => 'Evolução mensal intensa', 'effective_hourly_rate' => 'R$ 125/h', 'price' => 'R$ 5.000/mês'],
            ],
            'scope_limits' => [
                'Banco de horas não acumula automaticamente, salvo contrato específico.',
                'Novos módulos grandes devem virar projeto separado.',
            ],
            'commercial_notes' => [
                'Sustentação evita que o sistema envelheça sem acompanhamento.',
            ],
        ],
    ],

    'method' => [
        ['title' => 'Diagnóstico', 'objective' => 'Entender a dor e o cenário', 'deliverables' => 'Briefing, prioridades e recomendação'],
        ['title' => 'Discovery', 'objective' => 'Transformar ideia em escopo', 'deliverables' => 'Requisitos, fluxos, telas e roadmap'],
        ['title' => 'Design e Protótipo', 'objective' => 'Validar aparência e navegação', 'deliverables' => 'Wireframes ou protótipo navegável'],
        ['title' => 'Desenvolvimento', 'objective' => 'Construir a solução', 'deliverables' => 'Código, banco, telas e integrações'],
        ['title' => 'Homologação', 'objective' => 'Testar com o cliente', 'deliverables' => 'Correções e aceite'],
        ['title' => 'Deploy', 'objective' => 'Publicar em produção', 'deliverables' => 'Hospedagem, domínio, SSL e backups'],
        ['title' => 'Sustentação', 'objective' => 'Manter funcionando', 'deliverables' => 'Correções, suporte e melhorias'],
    ],

    'combined_packages' => [
        ['name' => 'Presença Digital Starter', 'best_for' => 'Profissional ou microempresa', 'includes' => 'Landing ou página comercial + publicação', 'starting_price' => 'R$ 1.500', 'suggested_monthly' => 'R$ 300/mês'],
        ['name' => 'Empresa Online Business', 'best_for' => 'Pequena empresa', 'includes' => 'Site institucional + manutenção profissional', 'starting_price' => 'R$ 7.500', 'suggested_monthly' => 'R$ 600/mês'],
        ['name' => 'Captação de Leads', 'best_for' => 'Campanha ou serviço recorrente', 'includes' => 'Landing + formulário + relatório + manutenção', 'starting_price' => 'R$ 4.500', 'suggested_monthly' => 'R$ 600/mês'],
        ['name' => 'Sistema Administrativo Starter', 'best_for' => 'Empresa em planilhas', 'includes' => 'Cadastros, login, relatórios simples e deploy', 'starting_price' => 'R$ 12.000', 'suggested_monthly' => 'R$ 700/mês'],
        ['name' => 'Gestão Sob Medida Business', 'best_for' => 'Operação administrativa', 'includes' => 'Módulos, permissões, dashboard e manutenção', 'starting_price' => 'R$ 25.000', 'suggested_monthly' => 'R$ 1.500/mês'],
        ['name' => 'Plataforma Gerenciada', 'best_for' => 'Produto digital ou operação maior', 'includes' => 'Sistema, integrações, homologação e evolução', 'starting_price' => 'R$ 90.000', 'suggested_monthly' => 'R$ 3.000/mês'],
    ],

    'commercial_rules' => [
        'Todo projeto deve ter escopo aprovado antes do início.',
        'Mudanças solicitadas após aprovação devem gerar aditivo de prazo e valor.',
        'Textos, fotos, vídeos, identidade visual e logotipo não estão inclusos, salvo contratação específica.',
        'Domínio, hospedagem, plugins, APIs pagas, gateways e serviços de terceiros são cobrados à parte.',
        'Integrações dependem das regras e limitações do fornecedor externo.',
        'A homologação deve ter prazo definido.',
        'Após o aceite, novas alterações entram como manutenção ou evolução.',
        'Projetos maiores podem ser divididos em fases para reduzir risco.',
        'Não vender ERP completo sem diagnóstico, escopo e implantação por etapas.',
    ],

    'not_included' => [
        'Criação de marca ou logotipo',
        'Redação profissional ou copywriting avançado',
        'Fotografia e vídeo',
        'Domínio',
        'Hospedagem',
        'Plugins pagos',
        'APIs pagas',
        'Gateways de pagamento',
        'Serviços de terceiros',
        'Licenças',
        'Manutenção após o prazo contratado, salvo plano mensal',
    ],
];
