<?php

$services = require __DIR__.'/sophdata_services.php';
$images = require __DIR__.'/sophdata_empresa_images.php';
$menu = require __DIR__.'/sophdata_empresa_menu.php';
$brand = (require __DIR__.'/sophdata.php')['brand'];

$mainBlocks = [
    [
        'slug' => 'desenvolvimento-de-software',
        'title' => 'Desenvolvimento de Software',
        'subtitle' => 'Sites, sistemas, automações e soluções digitais sob medida.',
        'description' => 'Criamos soluções digitais para organizar processos, substituir planilhas, melhorar a presença online e reduzir retrabalho na rotina da empresa.',
        'image' => $images['desenvolvimento'],
        'image_alt' => 'Soluções digitais e sistemas para empresas',
        'route' => '/para-empresas/desenvolvimento-de-software',
        'cta' => [
            'label' => 'Mapear minha solução',
            'url' => '/para-empresas/desenvolvimento-de-software',
        ],
        'whatsapp_message' => 'Olá! Quero entender como a SophData pode me ajudar com desenvolvimento de software para minha empresa.',
        'pains' => [
            'Empresa sem site profissional',
            'Site antigo ou difícil de atualizar',
            'Processos controlados por planilhas',
            'Retrabalho e digitação repetitiva',
            'Sistema sem suporte',
            'Falta de relatórios claros',
            'Dificuldade para publicar ou manter sistemas',
        ],
        'categories' => [
            'diagnostico-e-discovery',
            'sites-e-portais',
            'lojas-e-catalogos-digitais',
            'sistemas-sob-medida',
            'sistemas-por-segmento',
            'portais-area-logada-pwa',
            'automacoes-e-integracoes',
            'deploy-hospedagem',
            'sustentacao-e-evolucao',
        ],
        'config' => 'sophdata_desenvolvimento',
    ],
    [
        'slug' => 'infraestrutura-corporativa-gerenciada',
        'title' => 'Infraestrutura Corporativa Gerenciada',
        'subtitle' => 'Computadores, redes, Wi-Fi, suporte e administração mensal.',
        'description' => 'Organizamos a base tecnológica da empresa para que computadores, rede, Wi-Fi, impressoras e suporte funcionem com mais estabilidade, documentação e acompanhamento.',
        'image' => $images['infraestrutura'],
        'image_alt' => 'Infraestrutura corporativa com suporte, computadores e rede organizada',
        'route' => '/para-empresas/infraestrutura-corporativa-gerenciada',
        'cta' => [
            'label' => 'Avaliar minha infraestrutura',
            'url' => '/para-empresas/infraestrutura-corporativa-gerenciada',
        ],
        'whatsapp_message' => 'Olá! Quero avaliar a infraestrutura de TI da minha empresa com a SophData.',
        'pains' => [
            'Computadores lentos ou sem padrão',
            'Rede instável',
            'Wi-Fi fraco',
            'Impressoras com falhas recorrentes',
            'Falta de documentação técnica',
            'Suporte feito apenas no improviso',
            'Equipamentos sem inventário',
            'Falta de manutenção preventiva',
        ],
        'categories' => [
            'hardware-corporativo',
            'redes-corporativas',
            'wifi-corporativo',
            'administracao-mensal',
            'pacotes-integrados',
        ],
        'config' => 'sophdata_infraestrutura',
    ],
    [
        'slug' => 'servidores-e-ambientes-corporativos',
        'title' => 'Servidores e Ambientes Corporativos',
        'subtitle' => 'Arquivos, permissões, backup, VPN, virtualização e continuidade.',
        'description' => 'Implantamos e administramos ambientes corporativos para centralizar arquivos, controlar acessos, proteger dados e dar mais segurança à operação da empresa.',
        'image' => $images['servidores'],
        'image_alt' => 'Segurança, backup e servidores para ambientes corporativos',
        'route' => '/para-empresas/servidores-e-ambientes-corporativos',
        'cta' => [
            'label' => 'Avaliar meu ambiente',
            'url' => '/para-empresas/servidores-e-ambientes-corporativos',
        ],
        'whatsapp_message' => 'Olá! Quero avaliar servidores, backup ou ambiente corporativo para minha empresa com a SophData.',
        'pains' => [
            'Arquivos espalhados em várias máquinas',
            'Falta de controle de acesso',
            'Ausência de backup confiável',
            'Dificuldade para trabalho remoto seguro',
            'Servidor improvisado',
            'Falta de organização de usuários e permissões',
            'Risco de perda de dados importantes',
            'Ambientes sem monitoramento ou administração',
        ],
        'categories' => [
            'servidor-de-arquivos',
            'active-directory',
            'backup-empresarial',
            'vpn-e-trabalho-remoto',
            'virtualizacao',
        ],
        'config' => 'sophdata_servidores',
    ],
];

return [
    'slug' => 'para-empresas',
    'title' => 'Soluções de TI para empresas',
    'subtitle' => 'Software, infraestrutura e servidores organizados para empresas que precisam de tecnologia funcionando com clareza e continuidade.',
    'description' => 'A SophData ajuda empresas, igrejas, escolas, escritórios e organizações a organizar sistemas, computadores, redes, servidores e suporte em uma estrutura profissional de TI.',
    'seo' => [
        'title' => 'SophData para Empresas | Sites, Infraestrutura e Servidores',
        'description' => 'A SophData ajuda empresas a organizar tecnologia com sites, sistemas, automações, suporte, infraestrutura, servidores, backup e acompanhamento.',
        'canonical' => '/para-empresas',
        'og_title' => 'SophData para Empresas',
        'og_description' => 'Software, infraestrutura e servidores para empresas que precisam organizar tecnologia com clareza e continuidade.',
        'og_image' => 'img/sophdata/portals/business-hero.webp',
        'robots' => 'index, follow',
    ],
    'hero' => [
        'title' => 'Organize software, infraestrutura e servidores da sua empresa',
        'subtitle' => 'A SophData ajuda empresas a estruturar sistemas, suporte, redes, servidores, backup e atendimento técnico com mais clareza e acompanhamento.',
        'image' => $images['business_hero'],
        'image_alt' => 'Tecnologia empresarial organizada para software, infraestrutura e servidores',
        'primary_cta' => [
            'label' => 'Iniciar atendimento empresarial',
            'url' => '/para-empresas/contato',
            'whatsapp_message' => 'Olá! Quero solicitar um diagnóstico empresarial com a SophData.',
        ],
        'secondary_cta' => [
            'label' => 'Ver soluções para empresas',
            'url' => '#solucoes',
        ],
    ],
    'main_blocks' => $mainBlocks,
    'ctas' => [
        'business_diagnosis' => [
            'label' => 'Iniciar atendimento empresarial',
            'url' => '/para-empresas/contato',
            'whatsapp_message' => 'Olá! Quero solicitar um diagnóstico empresarial com a SophData.',
        ],
        'software_diagnosis' => [
            'label' => 'Solicitar análise inicial',
            'url' => '/para-empresas/contato',
            'whatsapp_message' => 'Olá! Quero solicitar um diagnóstico digital para minha empresa com a SophData.',
        ],
        'infrastructure_diagnosis' => [
            'label' => 'Solicitar análise de infraestrutura',
            'url' => '/para-empresas/contato',
            'whatsapp_message' => 'Olá! Quero avaliar a infraestrutura de TI da minha empresa com a SophData.',
        ],
        'servers_assessment' => [
            'label' => 'Solicitar análise do ambiente',
            'url' => '/para-empresas/contato',
            'whatsapp_message' => 'Olá! Quero avaliar servidores, backup ou ambiente corporativo para minha empresa com a SophData.',
        ],
        'plans' => [
            'label' => 'Ver planos empresariais',
            'url' => '/para-empresas/planos',
        ],
        'how_we_work' => [
            'label' => 'Método de atendimento',
            'url' => '/para-empresas/como-trabalhamos',
        ],
        'contact' => [
            'label' => 'Solicitar atendimento empresarial',
            'url' => '/para-empresas/contato',
        ],
    ],
    'audiences' => [
        'Empresas e escritórios',
        'Igrejas e organizações religiosas',
        'Escolas e cursos',
        'Consultórios e clínicas',
        'Imobiliárias',
        'Prestadores de serviço',
        'ONGs e associações',
        'Comércios locais',
    ],
    'business_pains' => [
        'Planilhas demais e pouca organização',
        'Computadores lentos ou sem padrão',
        'Rede e Wi-Fi instáveis',
        'Arquivos espalhados e sem controle',
        'Ausência de backup confiável',
        'Site antigo ou inexistente',
        'Sistemas sem manutenção',
        'Suporte técnico apenas quando algo quebra',
    ],
    'method_summary' => [
        [
            'title' => 'Diagnóstico',
            'description' => 'Entendemos o cenário atual, as dores e as prioridades da empresa.',
        ],
        [
            'title' => 'Planejamento',
            'description' => 'Organizamos a solução em etapas claras, com escopo e direção.',
        ],
        [
            'title' => 'Implantação',
            'description' => 'Executamos o serviço com cuidado técnico e foco na operação.',
        ],
        [
            'title' => 'Documentação',
            'description' => 'Registramos informações importantes para facilitar suporte e continuidade.',
        ],
        [
            'title' => 'Administração e evolução',
            'description' => 'Acompanhamos o ambiente, corrigimos problemas e planejamos melhorias.',
        ],
    ],
    'how_we_work' => [
        'slug' => 'como-trabalhamos',
        'title' => 'Como Trabalhamos',
        'subtitle' => 'Método, clareza e continuidade para organizar tecnologia nas empresas.',
        'description' => 'A SophData conduz projetos e atendimentos empresariais com diagnóstico, planejamento, implantação, documentação e acompanhamento, evitando soluções improvisadas e escopos confusos.',
        'image' => 'img/sophdata/cta/contact-banner.webp',
        'image_alt' => 'Método empresarial para organizar tecnologia com clareza e continuidade',
        'route' => '/para-empresas/como-trabalhamos',
        'seo' => [
            'title' => 'Método de Atendimento | Método Empresarial SophData',
            'description' => 'Conheça o método da SophData para diagnóstico, planejamento, escopo, implantação, documentação e acompanhamento de soluções empresariais.',
            'canonical' => '/para-empresas/como-trabalhamos',
            'og_image' => 'img/sophdata/cta/contact-banner.webp',
            'robots' => 'index, follow',
        ],
        'cta' => [
            'label' => 'Solicitar diagnóstico empresarial',
            'url' => '/para-empresas/contato',
            'whatsapp_message' => 'Olá! Quero solicitar um diagnóstico empresarial com a SophData.',
        ],
        'diagnosis' => [
            'title' => 'Antes da solução, vem o entendimento',
            'description' => 'Nem toda empresa precisa começar por um sistema grande, um servidor completo ou um contrato mensal amplo. O diagnóstico ajuda a identificar o melhor caminho.',
            'points' => [
                'Entender o cenário atual da empresa',
                'Identificar dores reais e prioridades',
                'Evitar contratação maior ou menor do que o necessário',
                'Definir escopo, limites e responsabilidades',
                'Organizar etapas para reduzir risco',
                'Recomendar o melhor caminho entre software, infraestrutura e servidores',
            ],
        ],
        'steps' => [
            [
                'title' => 'Diagnóstico',
                'description' => 'Entendemos o cenário atual, as dores e as prioridades da empresa.',
            ],
            [
                'title' => 'Planejamento',
                'description' => 'Organizamos a solução em etapas claras, com escopo, limites e direção.',
            ],
            [
                'title' => 'Proposta',
                'description' => 'Apresentamos o caminho recomendado, valores, prazos e responsabilidades.',
            ],
            [
                'title' => 'Execução ou implantação',
                'description' => 'Realizamos o serviço com cuidado técnico e foco na operação da empresa.',
            ],
            [
                'title' => 'Homologação ou validação',
                'description' => 'Conferimos o resultado com o cliente antes de considerar a entrega concluída.',
            ],
            [
                'title' => 'Documentação',
                'description' => 'Registramos informações importantes para facilitar suporte, continuidade e futuras melhorias.',
            ],
            [
                'title' => 'Administração e evolução',
                'description' => 'Acompanhamos o ambiente, corrigimos problemas e planejamos melhorias quando contratado.',
            ],
        ],
        'service_paths' => [
            [
                'title' => 'Desenvolvimento de Software',
                'description' => 'Em projetos de software, começamos entendendo o processo da empresa, transformamos a necessidade em escopo, validamos telas ou fluxos quando necessário, desenvolvemos a solução, homologamos com o cliente e planejamos sustentação ou evolução.',
                'steps' => ['Diagnóstico', 'Discovery', 'Protótipo ou definição de fluxos', 'Desenvolvimento', 'Homologação', 'Deploy', 'Sustentação'],
                'url' => '/para-empresas/desenvolvimento-de-software',
            ],
            [
                'title' => 'Infraestrutura Corporativa Gerenciada',
                'description' => 'Em infraestrutura, avaliamos computadores, rede, Wi-Fi, impressoras, suporte e documentação para propor organização, manutenção preventiva e administração mensal conforme o porte da empresa.',
                'steps' => ['Diagnóstico do ambiente', 'Inventário básico', 'Plano de organização', 'Implantação ou correção', 'Documentação', 'Suporte e administração mensal'],
                'url' => '/para-empresas/infraestrutura-corporativa-gerenciada',
            ],
            [
                'title' => 'Servidores e Ambientes Corporativos',
                'description' => 'Em servidores e ambientes corporativos, avaliamos arquivos, permissões, backup, acesso remoto e continuidade antes de propor implantação, administração ou melhoria do ambiente.',
                'steps' => ['Diagnóstico do ambiente', 'Mapeamento de usuários e dados', 'Definição de permissões e backup', 'Implantação', 'Validação de acesso e restauração', 'Administração mensal'],
                'url' => '/para-empresas/servidores-e-ambientes-corporativos',
            ],
        ],
        'contracting_models' => [
            [
                'title' => 'Diagnóstico',
                'description' => 'Para entender o cenário e indicar o melhor caminho antes de contratar algo maior.',
            ],
            [
                'title' => 'Projeto fechado',
                'description' => 'Para entregas com escopo definido, prazo, valor e critérios de aceite.',
            ],
            [
                'title' => 'Implantação',
                'description' => 'Para organizar computadores, redes, servidores, backup, VPN ou ambientes específicos.',
            ],
            [
                'title' => 'Administração mensal',
                'description' => 'Para manter suporte, documentação, acompanhamento e prevenção.',
            ],
            [
                'title' => 'Sustentação',
                'description' => 'Para manter sites, sistemas e ambientes em funcionamento.',
            ],
            [
                'title' => 'Evolução contínua',
                'description' => 'Para empresas que precisam melhorar software, processos ou infraestrutura ao longo do tempo.',
            ],
            [
                'title' => 'Banco de horas',
                'description' => 'Para demandas recorrentes, ajustes, melhorias e suporte planejado.',
            ],
        ],
        'scope_rules' => [
            'Toda proposta deve ter escopo aprovado antes do início.',
            'Mudanças após aprovação podem gerar novo prazo e novo valor.',
            'Serviços de terceiros, licenças, equipamentos e materiais podem ser cobrados à parte.',
            'Projetos maiores podem ser divididos em fases.',
            'Homologação e aceite devem ter prazo combinado.',
            'Administração mensal possui limites conforme o plano contratado.',
        ],
        'documentation' => [
            'title' => 'Documentação para não depender de improviso',
            'description' => 'Tecnologia empresarial precisa deixar rastros organizados: acessos, escopo, configurações, rotinas, decisões e próximos passos.',
            'points' => [
                'Registro de informações importantes do ambiente',
                'Orientação básica para o cliente',
                'Histórico de decisões e mudanças',
                'Apoio ao suporte futuro',
                'Redução da dependência de memória ou improviso',
                'Mais clareza para continuidade e evolução',
            ],
        ],
        'client_responsibilities' => [
            'Informar dores, prioridades e restrições do ambiente',
            'Disponibilizar acessos necessários quando combinados',
            'Validar escopo, textos, fluxos ou configurações',
            'Responder dúvidas em tempo adequado',
            'Aprovar etapas antes de avançar quando necessário',
            'Informar mudanças de prioridade ou regra de negócio',
        ],
    ],
    'contact_page' => [
        'slug' => 'contato',
        'title' => 'Contato Empresarial',
        'subtitle' => 'Solicite um diagnóstico ou orientação para organizar a tecnologia da sua empresa.',
        'description' => 'Conte o cenário atual. A SophData ajuda a identificar o melhor caminho entre desenvolvimento de software, infraestrutura gerenciada, servidores corporativos, backup e suporte mensal.',
        'image' => 'img/sophdata/cta/contact-banner.webp',
        'image_alt' => 'Contato empresarial para diagnóstico de tecnologia',
        'route' => '/para-empresas/contato',
        'seo' => [
            'title' => 'Solicitar Atendimento Empresarial | SophData',
            'description' => 'Solicite atendimento empresarial para organizar software, infraestrutura, servidores, backup, acessos ou suporte mensal.',
            'canonical' => '/para-empresas/contato',
            'og_image' => 'img/sophdata/cta/contact-banner.webp',
            'robots' => 'index, follow',
        ],
        'primary_cta' => [
            'label' => 'Chamar no WhatsApp',
            'url' => null,
            'whatsapp_message' => 'Olá! Quero solicitar um diagnóstico empresarial com a SophData.',
        ],
        'secondary_cta' => [
            'label' => 'Ver planos empresariais',
            'url' => '/para-empresas/planos',
        ],
        'contact_channels' => [
            [
                'type' => 'whatsapp',
                'title' => 'WhatsApp',
                'description' => 'Indicado para primeiro contato, dúvidas rápidas e solicitação de diagnóstico.',
                'label' => $brand['whatsapp_display'] ?? null,
                'value' => $brand['whatsapp'] ?? null,
                'message' => 'Olá! Quero solicitar um diagnóstico empresarial com a SophData.',
            ],
            [
                'type' => 'email',
                'title' => 'E-mail',
                'description' => 'Indicado para envio de informações mais detalhadas, documentos ou contexto do projeto.',
                'label' => $brand['email'] ?? null,
                'value' => $brand['email'] ?? null,
            ],
        ],
        'needs' => [
            [
                'title' => 'Desenvolvimento de Software',
                'description' => 'Sites, sistemas, automações, integrações, portais e sustentação para organizar processos e reduzir retrabalho.',
                'url' => '/para-empresas/desenvolvimento-de-software',
                'whatsapp_message' => 'Olá! Quero falar sobre desenvolvimento de software para minha empresa.',
            ],
            [
                'title' => 'Infraestrutura Corporativa Gerenciada',
                'description' => 'Computadores, rede, Wi-Fi, suporte, documentação e administração mensal para manter a operação mais estável.',
                'url' => '/para-empresas/infraestrutura-corporativa-gerenciada',
                'whatsapp_message' => 'Olá! Quero avaliar a infraestrutura de TI da minha empresa.',
            ],
            [
                'title' => 'Servidores e Ambientes Corporativos',
                'description' => 'Servidor de arquivos, permissões, backup, VPN, virtualização e ambientes corporativos para proteger dados e organizar acessos.',
                'url' => '/para-empresas/servidores-e-ambientes-corporativos',
                'whatsapp_message' => 'Olá! Quero avaliar servidores, backup ou ambiente corporativo para minha empresa.',
            ],
            [
                'title' => 'Planos Empresariais',
                'description' => 'Caminhos de contratação para diagnóstico, software, infraestrutura, servidores e suporte mensal.',
                'url' => '/para-empresas/planos',
                'whatsapp_message' => 'Olá! Quero entender qual plano da SophData faz mais sentido para minha empresa.',
            ],
            [
                'title' => 'Diagnóstico Empresarial',
                'description' => 'Para empresas que ainda não sabem por onde começar e precisam organizar prioridades antes de contratar.',
                'url' => '/para-empresas/contato',
                'whatsapp_message' => 'Olá! Quero solicitar um diagnóstico empresarial com a SophData.',
            ],
        ],
        'first_contact_checklist' => [
            'Nome da empresa ou organização',
            'Cidade e bairro, se houver necessidade de atendimento presencial',
            'Principal problema ou objetivo',
            'Quantidade aproximada de computadores ou usuários',
            'Se já existe site, sistema, servidor, backup ou rede estruturada',
            'Urgência do atendimento',
            'Melhor horário para retorno',
            'Se a necessidade é pontual, projeto fechado ou acompanhamento mensal',
        ],
        'initial_flow' => [
            [
                'title' => 'Você apresenta o cenário',
                'description' => 'Conte a necessidade principal, o problema atual e o objetivo da empresa.',
            ],
            [
                'title' => 'A SophData avalia o caminho',
                'description' => 'Identificamos se o caso envolve software, infraestrutura, servidores, backup, suporte ou diagnóstico.',
            ],
            [
                'title' => 'Organizamos a próxima etapa',
                'description' => 'Dependendo do caso, seguimos para diagnóstico, proposta, visita, reunião ou levantamento técnico.',
            ],
            [
                'title' => 'Definimos escopo e prioridade',
                'description' => 'Antes de executar, buscamos alinhar limites, prazos, responsabilidades e próximos passos.',
            ],
        ],
        'commercial_notes' => [
            'Diagnósticos ajudam a evitar contratação errada.',
            'Projetos maiores podem ser divididos em fases.',
            'Atendimentos presenciais dependem de disponibilidade e localização.',
            'Equipamentos, licenças, hospedagem e serviços de terceiros podem ser cobrados à parte.',
            'Administração mensal possui escopo e limites conforme o plano contratado.',
            'O primeiro contato não substitui diagnóstico técnico quando o ambiente é complexo.',
        ],
        'final_cta' => [
            'title' => 'Pronto para organizar a tecnologia da sua empresa?',
            'description' => 'Envie uma mensagem contando o cenário atual. A SophData ajuda a identificar o melhor caminho entre software, infraestrutura, servidores e suporte mensal.',
            'label' => 'Solicitar diagnóstico empresarial',
            'url' => '/para-empresas/contato',
            'whatsapp_message' => 'Olá! Quero solicitar um diagnóstico empresarial com a SophData.',
        ],
    ],
    'legacy_categories' => $services['business'],
    'menu' => $menu,
    'authority' => [
        'enabled' => true,
        'title' => 'Responsabilidade técnica e atendimento consultivo',
        'subtitle' => 'Soluções empresariais precisam de cuidado técnico, clareza comercial e acompanhamento responsável.',
        'name' => 'Cleiton Araújo',
        'role' => 'Responsável técnico pela SophData',
        'image' => $images['autoridade'],
        'image_alt' => 'Responsável técnico da SophData',
        'summary' => 'A SophData é conduzida por um responsável técnico com experiência prática em desenvolvimento de sistemas, suporte, redes, Linux, servidores e ambientes corporativos. Essa base permite avaliar o cenário da empresa com visão realista, propor soluções adequadas e acompanhar a continuidade da operação.',
        'highlights' => [
            'Experiência prática em suporte e infraestrutura de TI',
            'Atuação com desenvolvimento web e sistemas sob medida',
            'Vivência com Linux, redes, servidores e ambientes corporativos',
            'Atendimento consultivo para pequenas empresas, igrejas, escolas e organizações',
        ],
        'trust_points' => [
            'Diagnóstico antes da proposta',
            'Linguagem clara para decisão empresarial',
            'Implantação com documentação e orientação',
            'Acompanhamento para continuidade e evolução',
        ],
        'cta' => [
            'label' => 'Falar com o responsável técnico',
            'url' => '/para-empresas/contato',
            'whatsapp_message' => 'Olá! Quero falar com o responsável técnico da SophData sobre uma solução para minha empresa.',
        ],
    ],
    'cta' => [
        'title' => 'Quer organizar a tecnologia da sua empresa?',
        'description' => 'Conte o cenário atual. A SophData ajuda a identificar o melhor caminho entre software, infraestrutura, servidores e suporte mensal.',
        'primary_label' => 'Iniciar atendimento empresarial',
        'primary_url' => '/para-empresas/contato',
        'whatsapp_message' => 'Olá! Quero solicitar um diagnóstico empresarial com a SophData.',
        'image' => $images['contato'],
        'image_alt' => 'Atendimento empresarial para organizar tecnologia',
    ],
];
