<?php

return [
    'slug' => 'planos',
    'title' => 'Planos Empresariais',
    'subtitle' => 'Caminhos de contratação para organizar software, infraestrutura, servidores e suporte.',
    'description' => 'A SophData organiza planos empresariais para diferentes momentos da empresa: diagnóstico, presença digital, sistemas, infraestrutura, servidores, backup e administração mensal.',
    'image' => 'img/sophdata/portals/business-hero.webp',
    'image_alt' => 'Planos empresariais para organizar software, infraestrutura e servidores',
    'route' => '/para-empresas/planos',
    'seo' => [
        'title' => 'Planos Empresariais de TI | SophData',
        'description' => 'Planos empresariais para diagnóstico, desenvolvimento de software, infraestrutura gerenciada, servidores, backup e suporte mensal.',
        'canonical' => '/para-empresas/planos',
        'og_image' => 'img/sophdata/portals/business-hero.webp',
        'robots' => 'index, follow',
    ],
    'cta' => [
        'label' => 'Solicitar diagnóstico empresarial',
        'url' => '/para-empresas/contato',
        'whatsapp_message' => 'Olá! Quero entender qual plano da SophData faz mais sentido para minha empresa.',
    ],
    'selection_guide' => [
        [
            'need' => 'Preciso aparecer melhor na internet',
            'path' => 'Desenvolvimento de Software',
            'description' => 'Comecé por presença digital, site institucional, landing pagé ou portal.',
            'url' => '/para-empresas/desenvolvimento-de-software/sites-e-portais',
        ],
        [
            'need' => 'Minha empresa depende demais de planilhas',
            'path' => 'Sistemas e automações',
            'description' => 'Avalie sistema sob medida, automação, integração ou melhoria de fluxo interno.',
            'url' => '/para-empresas/desenvolvimento-de-software/sistemas-sob-medida',
        ],
        [
            'need' => 'Computadores, rede ou Wi-Fi dao problema',
            'path' => 'Infraestrutura Gerenciada',
            'description' => 'Organize computadores, rede, Wi-Fi, suporte e administração mensal.',
            'url' => '/para-empresas/infraestrutura-corporativa-gerenciada',
        ],
        [
            'need' => 'Arquivos e backup estão desorganizados',
            'path' => 'Servidores e Ambientes',
            'description' => 'Centralizé arquivos, controle acessos, organizé backup, VPN e continuidade.',
            'url' => '/para-empresas/servidores-e-ambientes-corporativos',
        ],
        [
            'need' => 'Não sei qual solução contratar',
            'path' => 'Diagnóstico empresarial',
            'description' => 'Comecé com uma avaliação para entender prioridade, risco e melhor caminho.',
            'url' => '/para-empresas/contato',
        ],
    ],
    'groups' => [
        [
            'slug' => 'diagnostico',
            'title' => 'Diagnóstico e primeiros passos',
            'description' => 'Para empresas que precisam entender o cenário antes de contratar um projeto maior.',
            'items' => [
                [
                    'name' => 'Diagnóstico Digital Express',
                    'indicated_for' => 'Microempresa, igreja ou pequeno negócio',
                    'includes' => ['Reunião de 1h', 'Recomendação por e-mail'],
                    'starting_price' => 'R$ 300',
                    'url' => '/para-empresas/desenvolvimento-de-software/diagnostico-e-discovery',
                ],
                [
                    'name' => 'Diagnóstico Comercial Digital',
                    'indicated_for' => 'Empresa sem presença digital clara',
                    'includes' => ['Analisé de site', 'WhatsApp', 'Jornada e oportunidades'],
                    'starting_price' => 'R$ 600',
                    'url' => '/para-empresas/desenvolvimento-de-software/diagnostico-e-discovery',
                ],
                [
                    'name' => 'Discovery de Sistema',
                    'indicated_for' => 'Empresa que desejá um sistema sob medida',
                    'includes' => ['Requisitos', 'Mapa de módulos', 'Escopo inicial'],
                    'starting_price' => 'R$ 1.500',
                    'url' => '/para-empresas/desenvolvimento-de-software/diagnostico-e-discovery',
                ],
                [
                    'name' => 'Diagnóstico de Infraestrutura',
                    'indicated_for' => 'Empresa com problemas em computadores, rede, Wi-Fi ou suporte',
                    'includes' => ['Avaliação do cenário', 'Levantamento de prioridades', 'Recomendação de próximos passos'],
                    'starting_price' => 'Sob avaliação',
                    'url' => '/para-empresas/infraestrutura-corporativa-gerenciada',
                ],
            ],
        ],
        [
            'slug' => 'desenvolvimento-de-software',
            'title' => 'Desenvolvimento de Software',
            'description' => 'Para empresas que precisam de site, sistema, automação, integração ou sustentação.',
            'items' => [
                [
                    'name' => 'Presença Digital Starter',
                    'indicated_for' => 'Profissional, microempresa ou campanha simples',
                    'includes' => ['Landing pagé ou página comercial', 'Publicação inicial'],
                    'starting_price' => 'A partir de R$ 1.500',
                    'monthly_suggestion' => 'A partir de R$ 300/mês',
                    'url' => '/para-empresas/desenvolvimento-de-software/sites-e-portais',
                ],
                [
                    'name' => 'Empresa Online Business',
                    'indicated_for' => 'Pequena empresa que precisa de site institucional',
                    'includes' => ['Site institucional', 'Organização de conteúdo', 'Manutenção profissional'],
                    'starting_price' => 'A partir de R$ 7.500',
                    'monthly_suggestion' => 'A partir de R$ 600/mês',
                    'url' => '/para-empresas/desenvolvimento-de-software/sites-e-portais',
                ],
                [
                    'name' => 'Sistema Administrativo Starter',
                    'indicated_for' => 'Empresa que usa planilhas para controlar processos',
                    'includes' => ['Login', 'Cadastros', 'Relatórios simples', 'Deploy'],
                    'starting_price' => 'A partir de R$ 12.000',
                    'monthly_suggestion' => 'A partir de R$ 700/mês',
                    'url' => '/para-empresas/desenvolvimento-de-software/sistemas-sob-medida',
                ],
                [
                    'name' => 'Gestão Sob Medida Business',
                    'indicated_for' => 'Operação administrativa com regras próprias',
                    'includes' => ['Módulos', 'Permissões', 'Dashboard', 'Manutenção'],
                    'starting_price' => 'A partir de R$ 25.000',
                    'monthly_suggestion' => 'A partir de R$ 1.500/mês',
                    'url' => '/para-empresas/desenvolvimento-de-software/sistemas-sob-medida',
                ],
                [
                    'name' => 'Sustentação Profissional',
                    'indicated_for' => 'Sistema em uso recorrente',
                    'includes' => ['Correções', 'Pequenos ajustes', 'Backup', 'Suporte'],
                    'monthly_suggestion' => 'A partir de R$ 1.500/mês',
                    'url' => '/para-empresas/desenvolvimento-de-software/sustentacao-e-evolucao',
                ],
            ],
        ],
        [
            'slug' => 'infraestrutura-corporativa-gerenciada',
            'title' => 'Infraestrutura Corporativa Gerenciada',
            'description' => 'Para empresas que precisam organizar computadores, rede, Wi-Fi, suporte e administração mensal.',
            'items' => [
                [
                    'name' => 'Infraestrutura Starter',
                    'indicated_for' => 'Microempresas, igrejas pequenas e escritórios com poucos computadores',
                    'limits' => ['Até 5 máquinas', 'Rede básica', 'Wi-Fi básico', 'Suporte remoto'],
                    'initial_implementation' => 'R$ 1.500',
                    'monthly_price' => 'R$ 600/mês',
                    'url' => '/para-empresas/infraestrutura-corporativa-gerenciada/pacotes-integrados',
                ],
                [
                    'name' => 'Infraestrutura Business',
                    'indicated_for' => 'Escritórios, consultorios, escolas pequenas e igrejas com estrutura administrativa',
                    'limits' => ['Até 15 máquinas', 'Rede profissional', 'Wi-Fi profissional', 'Servidor de arquivos', 'Backup profissional'],
                    'initial_implementation' => 'R$ 4.000',
                    'monthly_price' => 'R$ 1.200/mês',
                    'url' => '/para-empresas/infraestrutura-corporativa-gerenciada/pacotes-integrados',
                ],
                [
                    'name' => 'Infraestrutura Professional',
                    'indicated_for' => 'Empresas que dependem de computadores, rede, arquivos e servidor diáriamente',
                    'limits' => ['Até 30 máquinas', 'Rede gerenciada', 'Wi-Fi gerenciado', 'Servidor de arquivos', 'Backup corporativo'],
                    'initial_implementation' => 'R$ 8.000',
                    'monthly_price' => 'R$ 2.200/mês',
                    'url' => '/para-empresas/infraestrutura-corporativa-gerenciada/pacotes-integrados',
                ],
                [
                    'name' => 'Infraestrutura Corporativa',
                    'indicated_for' => 'Empresas maiores ou ambientes críticos',
                    'limits' => ['Até 50 máquinas', 'Rede avançada', 'Wi-Fi múltiplos ambientes', 'Servidor AD + arquivos', 'Backup corporativo'],
                    'initial_implementation' => 'R$ 12.000',
                    'monthly_price' => 'R$ 3.500/mês',
                    'url' => '/para-empresas/infraestrutura-corporativa-gerenciada/pacotes-integrados',
                ],
            ],
        ],
        [
            'slug' => 'servidores-e-ambientes-corporativos',
            'title' => 'Servidores e Ambientes Corporativos',
            'description' => 'Para empresas que precisam centralizar arquivos, controlar acessos, proteger dados, organizar VPN ou virtualização.',
            'items' => [
                [
                    'name' => 'Arquivos Protegidos',
                    'indicated_for' => 'Pequenas empresas que precisam centralizar documentos e proteger arquivos importantes',
                    'includes' => ['Servidor de Arquivos Starter ou Business', 'Backup Essencial ou Profissional', 'Administração mensal'],
                    'starting_price' => 'A partir de R$ 800',
                    'monthly_suggestion' => 'A partir de R$ 250/mês',
                    'url' => '/para-empresas/servidores-e-ambientes-corporativos/servidor-de-arquivos',
                ],
                [
                    'name' => 'Ambiente Corporativo Organizado',
                    'indicated_for' => 'Empresas que precisam de usuários, permissões e arquivos centralizados',
                    'includes' => ['Servidor de Arquivos', 'Active Directory', 'Backup Profissional', 'Administração mensal'],
                    'starting_price' => 'A partir de R$ 2.500',
                    'monthly_suggestion' => 'A partir de R$ 700/mês',
                    'url' => '/para-empresas/servidores-e-ambientes-corporativos',
                ],
                [
                    'name' => 'Trabalho Remoto com Controle',
                    'indicated_for' => 'Empresas com equipe externa, diretoria remota ou acesso fora do escritório',
                    'includes' => ['VPN', 'Servidor de Arquivos', 'Permissões de acesso', 'Administração mensal'],
                    'starting_price' => 'A partir de R$ 1.500',
                    'monthly_suggestion' => 'A partir de R$ 300/mês',
                    'url' => '/para-empresas/servidores-e-ambientes-corporativos/vpn-e-trabalho-remoto',
                ],
                [
                    'name' => 'Ambiente Gerenciado',
                    'indicated_for' => 'Empresas que dependem de servidor, backup, usuários e disponibilidade contínua',
                    'includes' => ['Servidor de Arquivos', 'Active Directory', 'Backup Corporativo', 'VPN', 'Administração mensal gerenciada'],
                    'starting_price' => 'Sob diagnóstico',
                    'monthly_suggestion' => 'A partir de R$ 1.500/mês',
                    'url' => '/para-empresas/servidores-e-ambientes-corporativos',
                ],
            ],
        ],
        [
            'slug' => 'administracao-mensal',
            'title' => 'Administração mensal e continuidade',
            'description' => 'Para empresas que precisam de acompanhamento, suporte, manutenção, documentação e evolução contínua.',
            'items' => [
                [
                    'name' => 'Site Care Essencial',
                    'indicated_for' => 'Site institucional simples',
                    'includes' => ['Backup', 'Atualizacao de conteúdo leve', 'Verificação mensal'],
                    'monthly_price' => 'R$ 300/mês',
                    'url' => '/para-empresas/desenvolvimento-de-software/sites-e-portais',
                ],
                [
                    'name' => 'Sustentação Profissional',
                    'indicated_for' => 'Sistema em uso recorrente',
                    'includes' => ['Correções', 'Pequenos ajustes', 'Backup', 'Suporte'],
                    'monthly_price' => 'R$ 1.500/mês',
                    'url' => '/para-empresas/desenvolvimento-de-software/sustentacao-e-evolucao',
                ],
                [
                    'name' => 'Hardware Care Profissional',
                    'indicated_for' => 'Escritório pequeno ou equipe administrativa',
                    'includes' => ['Preventiva', 'Inventario', 'Suporte local'],
                    'monthly_price' => 'R$ 650/mês',
                    'url' => '/para-empresas/infraestrutura-corporativa-gerenciada/hardware-corporativo',
                ],
                [
                    'name' => 'Administração Mensal de Redes',
                    'indicated_for' => 'Empresas com rede, Wi-Fi e impressoras em operação',
                    'includes' => ['Revisão', 'Documentação', 'Suporte e acompanhamento'],
                    'monthly_price' => 'A partir de R$ 250/mês',
                    'url' => '/para-empresas/infraestrutura-corporativa-gerenciada/administracao-mensal',
                ],
                [
                    'name' => 'Servidor Gerenciado',
                    'indicated_for' => 'Empresas com arquivos, backup ou permissões centralizadas',
                    'includes' => ['Backup', 'Monitoramento', 'Relatório e suporte'],
                    'monthly_price' => 'A partir de R$ 700/mês',
                    'url' => '/para-empresas/servidores-e-ambientes-corporativos/servidor-de-arquivos',
                ],
            ],
        ],
    ],
    'not_included' => [
        'Equipamentos físicos, peças, SSD, memória, cabos, roteadores, switches, access points e nobreaks',
        'Licenças Microsoft, Windows Server, Office, antivirus pago, plugins e softwares de terceiros',
        'Domínio, hospedagem, APIs pagas, gateways de pagamento e serviços externos',
        'Criacao de logotipo, fotografia, video ou copywriting avançado',
        'Serviços elétricos, infraestrutura predial, racks, patch panels e cabeamento estruturado completo',
        'Suporte fora do escopo mensal contratado',
    ],
    'commercial_notes' => [
        'Os valores apresentados servem como referencia inicial e podem variar conforme diagnóstico, escopo, porte do ambiente e necessidades específicas.',
        'Projetos maiores devem ser divididos em fases para reduzir risco e facilitar aprovacao.',
        'Toda contratação deve ter escopo, limites, prazos e responsabilidades definidos antes do inicio.',
        'Serviços mensais não substituem investimentos necessários em equipamentos, licenças ou infraestrutura física.',
        'Mudancas solicitadas após aprovacao de escopo podem gerar novo prazo e novo valor.',
    ],
];
