<?php

$contactUrl = '/para-empresas/contato';

$service = static fn (string $title, string $criterion, string $recommendedFor, string $price): array => [
    'title' => $title,
    'criterion' => $criterion,
    'recommended_for' => $recommendedFor,
    'price' => $price,
];

$package = static fn (string $title, array $items): array => array_filter([
    'title' => $title,
    ...$items,
], static fn ($value): bool => $value !== null && $value !== []);

$cta = static fn (string $label, string $message): array => [
    'label' => $label,
    'url' => $contactUrl,
    'whatsapp_message' => $message,
];

$integratedPackages = [
    $package('Infraestrutura Starter', [
        'recommended_for' => 'Microempresas, igrejas pequenas e escritórios com poucos computadores',
        'limits' => [
            'Máquinas até 5',
            'Rede básica',
            'Wi-Fi básico',
            'Servidor opcional',
            'Backup essencial',
            'Suporte remoto',
        ],
        'initial_price' => 'R$ 1.500',
        'monthly_price' => 'R$ 600/mes',
    ]),
    $package('Infraestrutura Business', [
        'recommended_for' => 'Escritórios, consultórios, escolas pequenas e igrejas com estrutura administrativa',
        'limits' => [
            'Máquinas até 15',
            'Rede profissional',
            'Wi-Fi profissional',
            'Servidor de arquivos',
            'Backup profissional',
            'Suporte remoto + visita',
        ],
        'initial_price' => 'R$ 4.000',
        'monthly_price' => 'R$ 1.200/mes',
    ]),
    $package('Infraestrutura Professional', [
        'recommended_for' => 'Empresas que dependem de computadores, rede, arquivos e servidor diáriamente',
        'limits' => [
            'Máquinas até 30',
            'Rede gerenciada',
            'Wi-Fi gerenciado',
            'Servidor de arquivos + permissões',
            'Backup corporativo',
            'Suporte prioridade',
        ],
        'initial_price' => 'R$ 8.000',
        'monthly_price' => 'R$ 2.200/mes',
    ]),
    $package('Infraestrutura Corporativa', [
        'recommended_for' => 'Empresas maiores ou ambientes críticos',
        'limits' => [
            'Máquinas até 50',
            'Rede avançada',
            'Wi-Fi múltiplos ambientes',
            'Servidor AD + arquivos',
            'Backup corporativo',
            'Suporte consultivo',
        ],
        'initial_price' => 'R$ 12.000',
        'monthly_price' => 'R$ 3.500/mes',
    ]),
];

return [
    'slug' => 'infraestrutura-corporativa-gerenciada',
    'title' => 'Infraestrutura Corporativa Gerenciada',
    'subtitle' => 'Computadores, redes, Wi-Fi, suporte e administração mensal.',
    'description' => 'Organizamos a base tecnologica da empresa para que computadores, rede, Wi-Fi, impressoras e suporte funcionem com mais estabilidade, documentação e acompanhamento.',
    'image' => 'img/sophdata/services/business/suporte-de-ti-hero.webp',
    'image_alt' => 'Infraestrutura corporativa com suporte, computadores e rede organizada',
    'route' => '/para-empresas/infraestrutura-corporativa-gerenciada',
    'seo' => [
        'title' => 'Infraestrutura Corporativa Gerenciada | SophData',
        'description' => 'Organização de computadores, redes, Wi-Fi, suporte, documentação e administração mensal para empresas que precisam de mais estabilidade.',
        'canonical' => '/para-empresas/infraestrutura-corporativa-gerenciada',
        'og_image' => 'img/sophdata/services/business/suporte-de-ti-hero.webp',
        'robots' => 'index, follow',
    ],
    'cta' => $cta(
        'Solicitar diagnóstico de infraestrutura',
        'Olá! Quero avaliar a infraestrutura de TI da minha empresa com a SophData.'
    ),
    'pains' => [
        'Computadores lentos ou sem padrao',
        'Rede instavel',
        'Wi-Fi fraco',
        'Impressoras com falhas recorrentes',
        'Falta de documentação técnica',
        'Suporte feito apenas no improviso',
        'Equipamentos sem inventário',
        'Falta de manutenção preventiva',
    ],
    'positioning' => [
        'Infraestrutura gerenciada organiza a operação diária da empresa, unindo computadores, rede, Wi-Fi, impressoras, documentação e suporte em uma rotina mais previsível.',
        'O foco é reduzir paradas, padronizar equipamentos, melhorar a produtividade da equipé e trocar o atendimento improvisado por acompanhamento contínuo.',
        'A SophData atua de forma consultiva para diagnosticar o ambiente, definir prioridades, executar melhorias e manter informações importantes registradas.',
    ],
    'logic' => [
        'O hardware e a estação de trabalho.',
        'A rede conecta a operação.',
        'O Wi-Fi amplia o acesso com mobilidade.',
        'A documentação reduz dependencia de improviso.',
        'A administração mensal mantém tudo em ordem.',
    ],
    'categories' => [
        [
            'slug' => 'hardware-corporativo',
            'title' => 'Hardware Corporativo',
            'subtitle' => 'Computadores e notebooks organizados para a rotina da empresa.',
            'description' => 'Cuidamos das estações de trabalho da empresa para reduzir lentidão, travamentos, improvisos técnicos e perda de produtividade. O objetivo é manter computadores padronizados, documentados e prontos para o uso diário.',
            'image' => 'img/sophdata/services/business/computadores-corporativos.webp',
            'image_alt' => 'Computadores corporativos preparados para a rotina da empresa',
            'route' => '/para-empresas/infraestrutura-corporativa-gerenciada/hardware-corporativo',
            'cta' => $cta(
                'Organizar meus computadores',
                'Olá! Quero organizar os computadores da minha empresa com a SophData.'
            ),
            'pains' => [
                'Computadores lentos',
                'Máquinas travando',
                'Notebooks superaquecendo',
                'Falta de espaço em disco',
                'HD antigo sem desempenho',
                'Falta de padronização',
                'Programas desatualizados',
                'Usuários sem suporte',
                'Equipamentos sem inventário',
                'Máquinas sem rotina preventiva',
                'Perda de tempo da equipe',
                'Compras de equipamentos sem critério técnico',
            ],
            'services' => [
                $service('Diagnóstico técnico', '1 equipamento', 'Falhas e lentidão', 'R$ 100'),
                $service('Visita técnica', '1a hora', 'Atendimento local', 'R$ 150'),
                $service('Hora técnica adicional', 'Por hora', 'Suporte local', 'R$ 100'),
                $service('Suporte remoto', 'Por hora', 'Ajustes simples', 'R$ 80'),
                $service('Formatação corporativa', '1 equipamento', 'Reinstalação limpa', 'R$ 250'),
                $service('Instalação de programas', '1 equipamento', 'Ambiente básico', 'R$ 120'),
                $service('Instalação de SSD', 'Mão de obra', 'Upgrade de desempenho', 'R$ 180'),
                $service('Upgrade de memória', 'Mão de obra', 'Desempenho', 'R$ 150'),
                $service('Limpeza preventiva', '1 equipamento', 'Manutenção física', 'R$ 150'),
                $service('Migração de arquivos', '1 equipamento', 'Troca de máquina', 'R$ 180'),
                $service('Configuração de impressora', 'Por impressora', 'Impressão local ou em rede', 'R$ 120'),
                $service('Laudo técnico simples', '1 equipamento', 'Troca ou baixa', 'R$ 150'),
                $service('Montagem de computador', 'Mão de obra', 'Estação nova', 'R$ 350'),
                $service('Montagem avançada', 'Mão de obra', 'Alto desempenho', 'R$ 500'),
                $service('Padronização de estação', '1 equipamento', 'Uso corporativo', 'R$ 300'),
            ],
            'implementation_packages' => [
                $package('Starter', [
                    'machines' => 'Até 3',
                    'profile' => 'Microempresa',
                    'includes' => ['Configuração básica'],
                    'price' => 'R$ 600',
                ]),
                $package('Business', [
                    'machines' => 'Até 8',
                    'profile' => 'Escritório pequeno',
                    'includes' => ['Padrão corporativo'],
                    'price' => 'R$ 1.500',
                ]),
                $package('Professional', [
                    'machines' => 'Até 15',
                    'profile' => 'Equipe administrativa',
                    'includes' => ['Padronização completa'],
                    'price' => 'R$ 2.800',
                ]),
                $package('Advanced', [
                    'machines' => 'Até 30',
                    'profile' => 'Operação maior',
                    'includes' => ['Inventario + padrao'],
                    'price' => 'R$ 5.000',
                ]),
            ],
            'implementation_includes' => [
                'Instalação do sistema',
                'Criacao de usuário local',
                'Instalação de navegadores',
                'Instalação de ferramentas de escritorio',
                'Instalação de antivirus',
                'Configuração de impressora',
                'Configuração de e-mail',
                'Organização inicial de pastas',
                'Configuração de acesso a rede',
                'Configuração de acesso ao servidor',
                'Padronização visual básica',
                'Checklist de entrega',
            ],
            'monthly_plans' => [
                $package('Essencial', [
                    'machines' => 'Até 5',
                    'attendance' => 'Remoto',
                    'preventive' => 'Trimestral',
                    'price' => 'R$ 300/mes',
                    'includes' => ['Suporte remoto', 'Orientação', 'Revisão básica'],
                ]),
                $package('Profissional', [
                    'machines' => 'Até 15',
                    'attendance' => 'Remoto + local',
                    'preventive' => 'Bimestral',
                    'price' => 'R$ 650/mes',
                    'includes' => ['Preventiva', 'Inventario', 'Suporte local'],
                ]),
                $package('Gerenciado', [
                    'machines' => 'Até 30',
                    'attendance' => 'Prioritario',
                    'preventive' => 'Mensal',
                    'price' => 'R$ 1.100/mes',
                    'includes' => ['Relatório', 'Padronização', 'Prioridade'],
                ]),
                $package('Corporativo', [
                    'machines' => 'Até 50',
                    'attendance' => 'Consultivo',
                    'preventive' => 'Mensal',
                    'price' => 'R$ 1.800/mes',
                    'includes' => ['Planejamento', 'Ciclo de vida', 'Visitas'],
                ]),
            ],
            'additional_modules' => [
                $package('Maquina adicional', ['criterion' => 'Por estação', 'price' => 'R$ 40/mes']),
                $package('Visita extra', ['criterion' => 'Por visita', 'price' => 'R$ 200']),
                $package('Preventiva extra', ['criterion' => 'Por estação', 'price' => 'R$ 100']),
                $package('Relatório de inventário', ['criterion' => 'Por ambiente', 'price' => 'R$ 300']),
                $package('Planejamento de upgrades', ['criterion' => 'Por projeto', 'price' => 'R$ 400']),
                $package('Apoio em compra técnica', ['criterion' => 'Por cotacao', 'price' => 'R$ 250']),
                $package('Preparação de imagem padrao', ['criterion' => 'Por modelo', 'price' => 'R$ 500']),
                $package('Documentação do parque', ['criterion' => 'Por ambiente', 'price' => 'R$ 400']),
            ],
            'recommended_profiles' => [
                $package('Igreja pequena', ['machines' => 'Até 5', 'need' => 'Secretaria', 'suggested_package' => 'Essencial']),
                $package('Consultorio', ['machines' => 'Até 8', 'need' => 'Recepcao', 'suggested_package' => 'Profissional']),
                $package('Escola pequena', ['machines' => 'Até 15', 'need' => 'Administrativo', 'suggested_package' => 'Profissional']),
                $package('Escritório contabil', ['machines' => 'Até 20', 'need' => 'Produtividade', 'suggested_package' => 'Gerenciado']),
                $package('Imobiliária', ['machines' => 'Até 30', 'need' => 'Operação', 'suggested_package' => 'Gerenciado']),
                $package('Empresa administrativa', ['machines' => 'Até 50', 'need' => 'Padronização', 'suggested_package' => 'Corporativo']),
            ],
            'commercial_combinations' => [
                $package('Estações em Ordem', [
                    'implementation' => 'Starter - R$ 600',
                    'maintenance' => 'Essencial - R$ 300/mes',
                    'initial_total' => 'R$ 600',
                    'monthly_total' => 'R$ 300/mes',
                ]),
                $package('Escritório Produtivo', [
                    'implementation' => 'Business - R$ 1.500',
                    'maintenance' => 'Profissional - R$ 650/mes',
                    'inventory' => 'Incluso',
                    'initial_total' => 'R$ 1.500',
                    'monthly_total' => 'R$ 650/mes',
                ]),
                $package('Parque Gerenciado', [
                    'implementation' => 'Professional - R$ 2.800',
                    'maintenance' => 'Gerenciado - R$ 1.100/mes',
                    'documentation' => 'Incluso',
                    'initial_total' => 'R$ 2.800',
                    'monthly_total' => 'R$ 1.100/mes',
                ]),
            ],
            'commercial_notes' => [
                'Valores consideram mao de obra técnica e podem variar conforme estado dos equipamentos, deslocamento, complexidade e necessidade de peças.',
            ],
        ],
        [
            'slug' => 'redes-corporativas',
            'title' => 'Redes Corporativas',
            'subtitle' => 'Conectividade organizada para a operação da empresa.',
            'description' => 'Organizamos a rede da empresa para que computadores, servidores, impressoras, internet e sistemas se comuniquem corretamente, com melhor controle, documentação e possibilidade de expansão.',
            'image' => 'img/sophdata/services/business/redes-e-wifi.webp',
            'image_alt' => 'Rede corporativa organizada para conectar computadores e sistemas',
            'route' => '/para-empresas/infraestrutura-corporativa-gerenciada/redes-corporativas',
            'cta' => $cta(
                'Avaliar minha rede',
                'Olá! Quero avaliar a rede da minha empresa com a SophData.'
            ),
            'pains' => [
                'Internet instavel',
                'Rede caindo',
                'Impressora que não imprime',
                'Computadores sem acesso ao servidor',
                'Cabeamento desorganizado',
                'Roteadores mal configurados',
                'Rede de visitantes sem separacao',
                'Falta de controle de IPs',
                'Falta de documentação',
                'Falta de segurança na rede',
                'Equipamentos antigos',
                'Rede sem padrao',
                'Dificuldade de expansão',
            ],
            'services' => [
                $service('Diagnóstico de rede', 'Ambiente pequeno', 'Falhas e lentidão', 'R$ 250'),
                $service('Mapeamento de rede', 'Até 10 pontos', 'Documentação', 'R$ 400'),
                $service('Configuração de roteador', 'Por equipamento', 'Internet', 'R$ 180'),
                $service('Configuração de switch', 'Por equipamento', 'Rede interna', 'R$ 250'),
                $service('Configuração de access point', 'Por unidade', 'Wi-Fi', 'R$ 200'),
                $service('Rede de visitantes', 'Por ambiente', 'Segurança', 'R$ 250'),
                $service('Compartilhamento de impressora', 'Por impressora', 'Impressão', 'R$ 120'),
                $service('Organização de IPs', 'Até 20 ativos', 'Padronização', 'R$ 300'),
                $service('Revisão de Wi-Fi', 'Até 2 pontos', 'Cobertura', 'R$ 350'),
                $service('Documentação de rede', 'Ambiente pequeno', 'Controle', 'R$ 500'),
                $service('Suporte a provedor', 'Por chamado', 'Internet', 'R$ 150'),
                $service('Configuração de VPN simples', 'Até 5 usuários', 'Acesso remoto', 'R$ 400'),
                $service('Revisão de segurança básica', 'Ambiente pequeno', 'Proteção', 'R$ 350'),
            ],
            'implementation_packages' => [
                $package('Starter', ['points' => 'Até 5', 'profile' => 'Microempresa', 'includes' => ['Rede básica'], 'price' => 'R$ 800']),
                $package('Business', ['points' => 'Até 10', 'profile' => 'Escritório', 'includes' => ['Pontos + switch'], 'price' => 'R$ 1.500']),
                $package('Professional', ['points' => 'Até 20', 'profile' => 'Operação maior', 'includes' => ['Organização + documentação'], 'price' => 'R$ 3.000']),
                $package('Advanced', ['points' => 'Até 40', 'profile' => 'Ambiente crítico', 'includes' => ['Projeto + documentação'], 'price' => 'R$ 6.000']),
            ],
            'implementation_includes' => [
                'Planejamento básico',
                'Identificação de pontos',
                'Organização logica',
                'Configuração de roteador',
                'Configuração de switch',
                'Configuração de impressoras',
                'Testes de conectividade',
                'Mapa simples da rede',
                'Documentação básica',
                'Orientação de uso',
            ],
            'monthly_plans' => [],
            'additional_modules' => [],
            'recommended_profiles' => [],
            'commercial_notes' => [
                'Os valores de implantação de rede não incluem cabos, canaletas, conectores, racks, patch panel, switches, roteadores, access points, serviços elétricos ou infraestrutura predial, salvo contratação específica.',
            ],
        ],
        [
            'slug' => 'wifi-corporativo',
            'title' => 'Wi-Fi Corporativo',
            'subtitle' => 'Cobertura e acesso sem fio com mais estabilidade e organização.',
            'description' => 'Planejamos e configuramos Wi-Fi corporativo para melhorar cobertura, acesso da equipe, rede de visitantes e estabilidade em ambientes empresariais.',
            'image' => 'img/sophdata/services/business/redes-e-wifi-hero.webp',
            'image_alt' => 'Wi-Fi corporativo com melhor cobertura e estabilidade',
            'route' => '/para-empresas/infraestrutura-corporativa-gerenciada/wifi-corporativo',
            'cta' => $cta(
                'Melhorar meu Wi-Fi',
                'Olá! Quero melhorar o Wi-Fi corporativo da minha empresa.'
            ),
            'pains' => [
                'Wi-Fi fraco',
                'Sinal instavel',
                'Áreas sem cobertura',
                'Muitos usuários no mesmo roteador',
                'Senhas compartilhadas sem controle',
                'Ausencia de rede de visitantes',
                'Dificuldade de separar acesso interno e externo',
                'Equipamentos mal posicionados',
            ],
            'services' => [],
            'implementation_packages' => [
                $package('Starter', ['área' => 'Até 80 m2', 'devices' => 'Até 10', 'includes' => ['1 ponto Wi-Fi'], 'price' => 'R$ 400']),
                $package('Business', ['área' => 'Até 200 m2', 'devices' => 'Até 30', 'includes' => ['2 pontos Wi-Fi'], 'price' => 'R$ 900']),
                $package('Professional', ['área' => 'Até 500 m2', 'devices' => 'Até 80', 'includes' => ['Múltiplos APs'], 'price' => 'R$ 2.000']),
                $package('Advanced', ['área' => 'Sob projeto', 'devices' => '80+', 'includes' => ['Wi-Fi gerenciado'], 'price' => 'R$ 4.000']),
            ],
            'implementation_includes' => [
                'Avaliação do ambiente',
                'Posicionamento de pontos',
                'Configuração de SSID',
                'Senha segura',
                'Rede de visitantes',
                'Separacao básica',
                'Teste de cobertura',
                'Orientação de uso',
            ],
            'monthly_plans' => [],
            'additional_modules' => [],
            'recommended_profiles' => [],
            'commercial_notes' => [
                'Equipamentos, cabeamento e infraestrutura física são cotados separadamente quando necessários.',
            ],
        ],
        [
            'slug' => 'administracao-mensal',
            'title' => 'Administração Mensal',
            'subtitle' => 'Acompanhamento contínuo para a infraestrutura da empresa.',
            'description' => 'A administração mensal mantém a infraestrutura acompanhada, documentada e assistida. O foco é reduzir improvisos, organizar suporte e prevenir problemas antes que eles prejudiquem a operação.',
            'image' => 'img/sophdata/services/business/suporte-de-ti.webp',
            'image_alt' => 'Administração mensal de TI com suporte e acompanhamento',
            'route' => '/para-empresas/infraestrutura-corporativa-gerenciada/administracao-mensal',
            'cta' => $cta(
                'Contratar administração mensal',
                'Olá! Quero falar sobre administração mensal de TI para minha empresa.'
            ),
            'pains' => [
                'Suporte apenas quando algo quebra',
                'Falta de rotina preventiva',
                'Ambiente sem documentação',
                'Problemas recorrentes sem análise',
                'Equipamentos sem acompanhamento',
                'Falta de prioridade no atendimento',
                'Dificuldade para planejar melhorias',
            ],
            'services' => [],
            'implementation_packages' => [],
            'monthly_plans' => [
                $package('Essencial', [
                    'assets' => 'Até 5',
                    'environment' => 'Simples',
                    'includes' => ['Suporte básico'],
                    'price' => 'R$ 250/mes',
                    'details' => ['Roteador', 'Wi-Fi', 'Impressora'],
                ]),
                $package('Profissional', [
                    'assets' => 'Até 15',
                    'environment' => 'Escritório',
                    'includes' => ['Revisão + documentação'],
                    'price' => 'R$ 500/mes',
                    'details' => ['IPs', 'Compartilhamentos', 'Revisão'],
                ]),
                $package('Gerenciado', [
                    'assets' => 'Até 30',
                    'environment' => 'Operação crítica',
                    'includes' => ['Monitoramento + relatório'],
                    'price' => 'R$ 900/mes',
                    'details' => ['Monitoramento', 'VPN', 'Relatório'],
                ]),
                $package('Corporativo', [
                    'assets' => 'Até 50',
                    'environment' => 'Multiambiente',
                    'includes' => ['Gestão consultiva'],
                    'price' => 'R$ 1.500/mes',
                    'details' => ['Planejamento', 'Expansão', 'Visitas'],
                ]),
            ],
            'additional_modules' => [
                $package('Ativo adicional', ['criterion' => 'Por equipamento', 'price' => 'R$ 40/mes']),
                $package('Ponto Wi-Fi adicional', ['criterion' => 'Por AP', 'price' => 'R$ 150/mes']),
                $package('Impressora adicional', ['criterion' => 'Por unidade', 'price' => 'R$ 30/mes']),
                $package('VPN adicional', ['criterion' => 'Por usuário', 'price' => 'R$ 20/mes']),
                $package('Visita extra', ['criterion' => 'Por visita', 'price' => 'R$ 200']),
                $package('Documentação avançada', ['criterion' => 'Por ambiente', 'price' => 'R$ 700']),
                $package('Segmentacao de rede', ['criterion' => 'Por projeto', 'price' => 'R$ 800']),
                $package('Rede de visitantes', ['criterion' => 'Por ambiente', 'price' => 'R$ 250']),
                $package('Firewall básico', ['criterion' => 'Por projeto', 'price' => 'R$ 700']),
                $package('Monitoramento simples', ['criterion' => 'Por ambiente', 'price' => 'R$ 300/mes']),
            ],
            'recommended_profiles' => [
                $package('Igreja pequena', ['machines' => 'Até 5', 'need' => 'Wi-Fi + secretaria', 'suggested_package' => 'Essencial']),
                $package('Consultorio', ['machines' => 'Até 8', 'need' => 'Wi-Fi + impressora', 'suggested_package' => 'Profissional']),
                $package('Escola pequena', ['machines' => 'Até 20', 'need' => 'Wi-Fi + rede cabeada', 'suggested_package' => 'Gerenciado']),
                $package('Escritório contabil', ['machines' => 'Até 20', 'need' => 'Servidor + rede', 'suggested_package' => 'Gerenciado']),
                $package('Imobiliária', ['machines' => 'Até 30', 'need' => 'Dados + acesso remoto', 'suggested_package' => 'Gerenciado']),
                $package('Empresa administrativa', ['machines' => 'Até 50', 'need' => 'Rede estruturada', 'suggested_package' => 'Corporativo']),
            ],
            'commercial_notes' => [
                'A administração mensal organiza acompanhamento, prioridade e documentação, mas não substitui investimento em equipamentos quando há obsolescência ou limitação física.',
            ],
        ],
        [
            'slug' => 'pacotes-integrados',
            'title' => 'Pacotes Integrados',
            'subtitle' => 'Infraestrutura organizada por porte de empresa.',
            'description' => 'Para empresas que não sabem por onde começar, os pacotes integrados reunem computadores, rede, Wi-Fi, servidor opcional, backup e suporte mensal em uma proposta mais simples de entender.',
            'image' => 'img/sophdata/portals/business-hero.webp',
            'image_alt' => 'Pacotes integrados de infraestrutura para empresas',
            'route' => '/para-empresas/infraestrutura-corporativa-gerenciada/pacotes-integrados',
            'cta' => $cta(
                'Escolher pacote empresarial',
                'Olá! Quero entender qual pacote de infraestrutura faz sentido para minha empresa.'
            ),
            'pains' => [
                'Dificuldade para saber por onde começar',
                'Computadores, rede e suporte tratados separadamente',
                'Ambiente sem plano de evolução',
                'Falta de previsibilidade nos custos de TI',
            ],
            'services' => [],
            'implementation_packages' => $integratedPackages,
            'monthly_plans' => [],
            'additional_modules' => [],
            'recommended_profiles' => [],
            'commercial_notes' => [
                'Pacotes integrados dependem de diagnóstico prévio para confirmar escopo, ambiente, equipamentos e prioridades.',
            ],
        ],
    ],
    'integrated_packages' => $integratedPackages,
    'commercial_combinations' => [
        $package('Rede Básica Organizada', [
            'wired_network' => 'Starter - R$ 800',
            'wifi' => 'Starter - R$ 400',
            'administration' => 'Essencial - R$ 250/mes',
            'initial_total' => 'R$ 1.200',
            'monthly_total' => 'R$ 250/mes',
        ]),
        $package('Escritório Conectado', [
            'wired_network' => 'Business - R$ 1.500',
            'wifi' => 'Business - R$ 900',
            'administration' => 'Profissional - R$ 500/mes',
            'initial_total' => 'R$ 2.400',
            'monthly_total' => 'R$ 500/mes',
        ]),
        $package('Rede Corporativa Gerenciada', [
            'wired_network' => 'Professional - R$ 3.000',
            'wifi' => 'Professional - R$ 2.000',
            'administration' => 'Gerenciado - R$ 900/mes',
            'documentation' => 'Incluso',
            'initial_total' => 'R$ 5.000',
            'monthly_total' => 'R$ 900/mês',
        ]),
    ],
    'commercial_rules' => [
        'Todo serviço deve ter escopo aprovado antes do início.',
        'Valores de implantação consideram mão de obra técnica, não equipamentos.',
        'Peças, licenças, cabos, conectores, racks, roteadores, switches, access points e materiais são cobrados à parte, salvo contratação específica.',
        'Serviços elétricos e infraestrutura predial não estão inclusos.',
        'Visitas fora do escopo contratado podem gerar cobrança adicional.',
        'Ambientes maiores ou críticos exigem diagnóstico prévio.',
        'Administração mensal não substitui investimento em equipamentos quando há limitação física ou obsolescência.',
        'Documentação técnica será proporcional ao pacote contratado.',
        'Mudanças de escopo podem gerar novo prazo e novo valor.',
    ],
    'not_included' => [
        'Peças',
        'SSD',
        'Memoria RAM',
        'Fontes',
        'Placas',
        'Cabos',
        'Canaletas',
        'Conectores',
        'Racks',
        'Patch panel',
        'Switches',
        'Roteadores',
        'Access points',
        'Licenças Microsoft',
        'Antivirus pago',
        'Office',
        'Serviços elétricos',
        'Infraestrutura predial',
        'Internet ou mensalidade de provedor',
        'Equipamentos de backup',
        'Nobreaks',
    ],
];
