<?php

$contactUrl = '/para-empresas/contato';

$package = static fn (string $title, array $items): array => array_filter([
    'title' => $title,
    ...$items,
], static fn ($value): bool => $value !== null && $value !== []);

$cta = static fn (string $label, string $message): array => [
    'label' => $label,
    'url' => $contactUrl,
    'whatsapp_message' => $message,
];

return [
    'slug' => 'servidores-e-ambientes-corporativos',
    'title' => 'Servidores e Ambientes Corporativos',
    'subtitle' => 'Arquivos, permissões, backup, VPN, virtualização e continuidade.',
    'description' => 'Implantamos e administramos ambientes corporativos para centralizar arquivos, controlar acessos, proteger dados e dar mais segurança a operação da empresa.',
    'image' => 'img/sophdata/services/business/seguranca-e-backup-hero.webp',
    'image_alt' => 'Segurança, backup e servidores para ambientes corporativos',
    'route' => '/para-empresas/servidores-e-ambientes-corporativos',
    'seo' => [
        'title' => 'Servidores e Ambientes Corporativos | SophData',
        'description' => 'Servidor de arquivos, Active Directory, backup empresarial, VPN e virtualização para empresas que precisam proteger dados e organizar acessos.',
        'canonical' => '/para-empresas/servidores-e-ambientes-corporativos',
        'og_image' => 'img/sophdata/services/business/seguranca-e-backup-hero.webp',
        'robots' => 'index, follow',
    ],
    'cta' => $cta(
        'Avaliar meu ambiente',
        'Olá! Quero avaliar servidores, backup ou ambiente corporativo para minha empresa com a SophData.'
    ),
    'pains' => [
        'Arquivos espalhados em várias máquinas',
        'Falta de controle de acesso',
        'Ausência de backup confiável',
        'Dificuldade para trabalho remoto seguro',
        'Servidor improvisado',
        'Falta de organização de usuários e permissões',
        'Risco de perda de dados importantes',
        'Ambientes sem monitoramento ou administração',
    ],
    'positioning' => [
        'Servidores e ambientes corporativos organizam informações importantes, acessos, backup e continuidade em uma estrutura mais segura para a empresa.',
        'A proposta e reduzir improvisos, centralizar arquivos, controlar permissões e manter recursos críticos acompanhados por administração mensal.',
        'A SophData trabalha com diagnóstico, implantação, documentação e acompanhamento para que a operação dependa menos de solução emergencial.',
    ],
    'logic' => [
        'O servidor centraliza os dados.',
        'As permissões organizam o acesso.',
        'O backup protegé a empresa.',
        'A VPN permite trabalho remoto com mais controle.',
        'A virtualização ajuda a organizar serviços e ambientes.',
        'A administração mensal mantém tudo acompanhado.',
    ],
    'categories' => [
        [
            'slug' => 'servidor-de-arquivos',
            'title' => 'Servidor de Arquivos',
            'subtitle' => 'Arquivos centralizados, permissões organizadas e acesso mais controlado.',
            'description' => 'Implantamos servidor de arquivos corporativo para centralizar documentos, organizar permissões por usuário ou setor e reduzir o risco de perda, duplicacao ou descontrole das informações da empresa.',
            'image' => 'img/sophdata/services/business/seguranca-e-backup-hero.webp',
            'image_alt' => 'Servidor de arquivos com dados centralizados e permissões organizadas',
            'route' => '/para-empresas/servidores-e-ambientes-corporativos/servidor-de-arquivos',
            'cta' => $cta(
                'Centralizar meus arquivos',
                'Olá! Quero centralizar arquivos e organizar permissões na minha empresa.'
            ),
            'pains' => [
                'Arquivos espalhados em computadores diferentes',
                'Documentos duplicados ou dificeis de localizar',
                'Falta de controle sobre quem acessa cada pasta',
                'Compartilhamentos improvisados',
                'Risco de perda de arquivos importantes',
                'Ausência de rotina de backup',
                'Dificuldade de organizar setores e permissões',
                'Falta de acesso remoto seguro aos documentos',
            ],
            'implementation_packages' => [
                $package('Starter', ['users' => 'Até 5', 'computers' => 'Até 5', 'includes' => ['Compartilhamento básico de arquivos'], 'price' => 'R$ 800']),
                $package('Business', ['users' => 'Até 15', 'computers' => 'Até 15', 'includes' => ['Permissões por departamento', 'Backup'], 'price' => 'R$ 1.500']),
                $package('Professional', ['users' => 'Até 30', 'computers' => 'Até 30', 'includes' => ['Permissões', 'Backup', 'VPN'], 'price' => 'R$ 2.500']),
            ],
            'monthly_plans' => [
                $package('Essencial', ['includes' => ['Atualizações', 'Suporte remoto'], 'price' => 'R$ 250/mês']),
                $package('Profissional', ['includes' => ['Atualizações', 'Backup supervisionado'], 'price' => 'R$ 450/mês']),
                $package('Gerenciado', ['includes' => ['Backup', 'Monitoramento', 'Relatório'], 'price' => 'R$ 700/mês']),
            ],
            'services' => [
                'Centralizacao de documentos',
                'Organização de pastas por setor',
                'Configuração de permissões',
                'Compartilhamento de arquivos',
                'Orientação de uso',
                'Documentação básica do ambiente',
            ],
            'commercial_notes' => [
                'Os valores consideram implantação e configuração do ambiente, não aquisição de servidor físico, storage, discos, nobreaks ou licenças.',
                'Ambientes com mais de 30 usuários exigem diagnóstico.',
                'Backup depende de mídia, armazenamento ou serviço contratado a parte.',
                'Acesso remoto deve ser configurado com critérios de segurança.',
            ],
        ],
        [
            'slug' => 'active-directory',
            'title' => 'Active Directory',
            'subtitle' => 'Usuários, computadores e permissões com mais controle.',
            'description' => 'Implantamos e administramos ambientes com controle centralizado de usuários, computadores e permissões, ajudando a empresa a organizar acessos, padronizar regras e reduzir improvisos na gestão da equipe.',
            'image' => 'img/sophdata/services/business/suporte-de-ti-hero.webp',
            'image_alt' => 'Active Directory para usuários, computadores e permissões corporativas',
            'route' => '/para-empresas/servidores-e-ambientes-corporativos/active-directory',
            'cta' => $cta(
                'Organizar usuários e permissões',
                'Olá! Quero organizar usuários, computadores e permissões na minha empresa.'
            ),
            'pains' => [
                'Usuários criados de forma improvisada',
                'Computadores sem padrão de acesso',
                'Senhas e permissões sem controle',
                'Dificuldade para bloquear ou liberar acessos',
                'Falta de organização por setor',
                'Ausência de políticas básicas',
                'Ambiente crescendo sem gestão centralizada',
                'Falta de auditoria básica',
            ],
            'implementation_packages' => [
                $package('Starter', ['users' => 'Até 10', 'computers' => 'Até 10', 'price' => 'R$ 1.000']),
                $package('Business', ['users' => 'Até 25', 'computers' => 'Até 25', 'price' => 'R$ 2.000']),
                $package('Professional', ['users' => 'Até 50', 'computers' => 'Até 50', 'price' => 'R$ 3.500']),
            ],
            'monthly_plans' => [
                $package('Essencial', ['includes' => ['Usuários e permissões'], 'price' => 'R$ 300/mês']),
                $package('Profissional', ['includes' => ['GPO', 'Auditoria básica'], 'price' => 'R$ 500/mês']),
                $package('Gerenciado', ['includes' => ['GPO', 'Auditoria', 'Relatórios'], 'price' => 'R$ 800/mês']),
            ],
            'services' => [
                'Organização de usuários',
                'Organização de computadores',
                'Permissões por setor',
                'Padronização de regras',
                'Bloqueio e liberacao de acessos',
                'Documentação básica',
            ],
            'commercial_notes' => [
                'Licenças Microsoft, servidor físico, Windows Server e CALs não estão inclusos, salvo contratação específica.',
                'Ambientes com regras avançadas exigem diagnóstico.',
                'Políticas de segurança devem respeitar o porte e a maturidade da empresa.',
                'Integração com backup, VPN ou servidor de arquivos pode ser vendida como pacote complementar.',
            ],
        ],
        [
            'slug' => 'backup-empresarial',
            'title' => 'Backup Empresarial',
            'subtitle' => 'Proteção contra perda de dados importantes.',
            'description' => 'Estruturamos rotinas de backup para proteger arquivos e informações críticas da empresa, com acompanhamento, relatórios e testes de restauração conforme o plano contratado.',
            'image' => 'img/sophdata/services/business/seguranca-e-backup.webp',
            'image_alt' => 'Backup empresarial para proteger dados importantes',
            'route' => '/para-empresas/servidores-e-ambientes-corporativos/backup-empresarial',
            'cta' => $cta(
                'Proteger meus dados',
                'Olá! Quero proteger os dados da minha empresa com uma solução de backup.'
            ),
            'pains' => [
                'Arquivos importantes sem copia de segurança',
                'Backup feito manualmente ou sem conferência',
                'Risco de perda por falha de computador ou servidor',
                'Ausência de teste de restauração',
                'Falta de relatório de backup',
                'Dados espalhados em máquinas sem proteção',
                'Dependência de pendrive ou HD externo sem rotina',
                'Preocupacao com continuidade após incidentes',
            ],
            'implementation_packages' => [],
            'monthly_plans' => [
                $package('Backup Essencial - 250 GB', ['storage' => '250 GB', 'tier' => 'Essencial', 'price' => 'R$ 180/mês']),
                $package('Backup Essencial - 500 GB', ['storage' => '500 GB', 'tier' => 'Essencial', 'price' => 'R$ 250/mês']),
                $package('Backup Essencial - 1 TB', ['storage' => '1 TB', 'tier' => 'Essencial', 'price' => 'R$ 350/mês']),
                $package('Backup Profissional - 250 GB', ['storage' => '250 GB', 'tier' => 'Profissional', 'includes' => ['Monitoramento', 'Relatórios', 'Teste de restauração'], 'price' => 'R$ 250/mês']),
                $package('Backup Profissional - 500 GB', ['storage' => '500 GB', 'tier' => 'Profissional', 'includes' => ['Monitoramento', 'Relatórios', 'Teste de restauração'], 'price' => 'R$ 350/mês']),
                $package('Backup Profissional - 1 TB', ['storage' => '1 TB', 'tier' => 'Profissional', 'includes' => ['Monitoramento', 'Relatórios', 'Teste de restauração'], 'price' => 'R$ 500/mês']),
                $package('Backup Corporativo - 1 TB', ['storage' => '1 TB', 'tier' => 'Corporativo', 'includes' => ['Retenção avançada', 'Monitoramento', 'Testes periódicos'], 'price' => 'R$ 600/mês']),
                $package('Backup Corporativo - 2 TB', ['storage' => '2 TB', 'tier' => 'Corporativo', 'includes' => ['Retenção avançada', 'Monitoramento', 'Testes periódicos'], 'price' => 'R$ 850/mês']),
                $package('Backup Corporativo - 5 TB', ['storage' => '5 TB', 'tier' => 'Corporativo', 'includes' => ['Retenção avançada', 'Monitoramento', 'Testes periódicos'], 'price' => 'R$ 1.500/mês']),
            ],
            'services' => [
                'Planejamento da rotina de backup',
                'Configuração de copia de segurança',
                'Monitoramento conforme plano',
                'Relatórios conforme plano',
                'Teste de restauração conforme plano',
                'Orientação sobre armazenamento local, nuvem ou híbrido',
            ],
            'commercial_notes' => [
                'O plano deve considerar volume de dados, frequência de backup, retenção e criticidade da operação.',
                'Backup não substitui organização de arquivos e permissões.',
                'O teste de restauração e essencial para validar a confiabilidade do backup.',
                'Armazenamento local, em nuvem ou híbrido deve ser definido em diagnóstico.',
                'Custos de serviços de nuvem, storage, discos ou licenças podem ser cobrados a parte.',
            ],
        ],
        [
            'slug' => 'vpn-e-trabalho-remoto',
            'title' => 'VPN e Trabalho Remoto',
            'subtitle' => 'Acesso remoto com mais controle para equipes externas.',
            'description' => 'Configuramos acesso remoto por VPN para permitir que usuários autorizados acessem recursos da empresa com mais controle, reduzindo improvisos e aumentando a segurança do trabalho remoto.',
            'image' => 'img/sophdata/services/business/redes-e-wifi-hero.webp',
            'image_alt' => 'VPN e trabalho remoto seguro para equipes empresariais',
            'route' => '/para-empresas/servidores-e-ambientes-corporativos/vpn-e-trabalho-remoto',
            'cta' => $cta(
                'Liberar acesso remoto seguro',
                'Olá! Quero organizar acesso remoto seguro para minha empresa.'
            ),
            'pains' => [
                'Equipe precisa acessar arquivos fora da empresa',
                'Trabalho remoto feito por soluções improvisadas',
                'Acesso externo sem controle adequado',
                'Dificuldade de conectar usuários ao servidor',
                'Necessidade de acesso remoto para diretoria ou equipe administrativa',
                'Falta de organização de usuários remotos',
                'Risco de exposição indevida de arquivos ou sistemas',
            ],
            'implementation_packages' => [
                $package('Starter', ['remote_users' => 'Até 5', 'price' => 'R$ 400']),
                $package('Business', ['remote_users' => 'Até 15', 'price' => 'R$ 800']),
                $package('Professional', ['remote_users' => 'Até 30', 'price' => 'R$ 1.500']),
            ],
            'monthly_plans' => [
                $package('Essencial', ['price' => 'R$ 100/mês']),
                $package('Profissional', ['price' => 'R$ 200/mês']),
                $package('Gerenciado', ['price' => 'R$ 300/mês']),
            ],
            'services' => [
                'Configuração de acesso remoto',
                'Organização de usuários autorizados',
                'Orientação de uso',
                'Ajustes em roteador, firewall ou servidor quando aplicável',
                'Documentação básica do acesso',
            ],
            'commercial_notes' => [
                'A VPN depende de internet estável, roteador compatível ou servidor adequado.',
                'Usuários adicionais podem gerar cobrança mensal extra.',
                'Acesso remoto deve ser limitado ao que cada usuário realmente precisa.',
                'A configuração pode exigir ajustes no provedor, firewall, roteador ou servidor.',
                'Em ambientes críticos, recomenda-se diagnóstico de segurança antes da implantação.',
            ],
        ],
        [
            'slug' => 'virtualizacao',
            'title' => 'Virtualização',
            'subtitle' => 'Ambientes organizados para serviços, testes e operação.',
            'description' => 'Implantamos ambientes virtualizados para organizar serviços, separar funções, facilitar manutenção e dar mais flexibilidade a infraestrutura da empresa.',
            'image' => 'img/sophdata/services/business/computadores-corporativos-hero.webp',
            'image_alt' => 'Virtualização para organizar serviços e ambientes corporativos',
            'route' => '/para-empresas/servidores-e-ambientes-corporativos/virtualizacao',
            'cta' => $cta(
                'Avaliar virtualização',
                'Olá! Quero avaliar virtualização para o ambiente da minha empresa.'
            ),
            'pains' => [
                'Muitos serviços misturados em uma única máquina',
                'Dificuldade para separar ambientes',
                'Necessidade de servidor para arquivos, sistemas ou testes',
                'Falta de flexibilidade para expansão',
                'Ambientes sem organização',
                'Dificuldade para manutenção sem parar tudo',
                'Necessidade de melhor aproveitamento de hardware',
            ],
            'implementation_packages' => [
                $package('Starter', ['virtual_machines' => 'Até 3', 'price' => 'R$ 2.000']),
                $package('Business', ['virtual_machines' => 'Até 8', 'price' => 'R$ 4.000']),
                $package('Professional', ['virtual_machines' => 'Até 15', 'price' => 'R$ 8.000']),
            ],
            'monthly_plans' => [
                $package('Essencial', ['price' => 'R$ 300/mês']),
                $package('Profissional', ['price' => 'R$ 600/mês']),
                $package('Gerenciado', ['price' => 'R$ 1.000/mês']),
            ],
            'services' => [
                'Organização de máquinas virtuais',
                'Separação de serviços',
                'Planejamento de capacidade',
                'Documentação do ambiente',
                'Orientação sobre backup das máquinas virtuais',
            ],
            'commercial_notes' => [
                'Hardware, storage, licenças e sistemas operacionais não estão inclusos, salvo contratação específica.',
                'Ambientes de virtualização exigem avaliação de capacidade.',
                'Backup das máquinas virtuais deve ser contratado ou planejado separadamente.',
                'Ambientes críticos devem ter estratégia de recuperação e documentação.',
            ],
        ],
    ],
    'recommended_bundles' => [
        $package('Arquivos Protegidos', [
            'recommended_for' => 'Pequenas empresas que precisam centralizar documentos e proteger arquivos importantes.',
            'includes' => [
                'Servidor de Arquivos Starter ou Business',
                'Backup Essencial ou Profissional',
                'Administração mensal',
            ],
            'initial_price' => 'A partir de R$ 800',
            'monthly_price' => 'A partir de R$ 250/mês',
        ]),
        $package('Ambiente Corporativo Organizado', [
            'recommended_for' => 'Empresas que precisam de usuários, permissões e arquivos centralizados.',
            'includes' => [
                'Servidor de Arquivos',
                'Active Directory',
                'Backup Profissional',
                'Administração mensal',
            ],
            'initial_price' => 'A partir de R$ 2.500',
            'monthly_price' => 'A partir de R$ 700/mês',
        ]),
        $package('Trabalho Remoto com Controle', [
            'recommended_for' => 'Empresas com equipe externa, diretoria remota ou necessidade de acesso fora do escritório.',
            'includes' => [
                'VPN',
                'Servidor de Arquivos',
                'Permissões de acesso',
                'Administração mensal',
            ],
            'initial_price' => 'A partir de R$ 1.500',
            'monthly_price' => 'A partir de R$ 300/mês',
        ]),
        $package('Ambiente Gerenciado', [
            'recommended_for' => 'Empresas que dependem de servidor, backup, usuários e disponibilidade contínua.',
            'includes' => [
                'Servidor de Arquivos',
                'Active Directory',
                'Backup Corporativo',
                'VPN',
                'Administração mensal gerenciada',
            ],
            'initial_price' => 'Sob diagnóstico',
            'monthly_price' => 'A partir de R$ 1.500/mês',
        ]),
    ],
    'commercial_rules' => [
        'Todo ambiente de servidor deve ter diagnóstico antes da implantação.',
        'Valores de implantação consideram mão de obra técnica, não equipamentos.',
        'Servidores físicos, storages, discos, nobreaks, roteadores, firewalls e licenças são cobrados à parte, salvo contratação específica.',
        'Licenças Microsoft, Windows Server, CALs, antivírus e softwares pagos não estão inclusos automaticamente.',
        'Backup depende de volume de dados, local de armazenamento, frequência e retenção.',
        'VPN depende de internet, roteador, firewall ou servidor compatível.',
        'Ambientes críticos exigem política de backup, documentação e administração mensal.',
        'Mudanças de escopo podem gerar novo prazo e novo valor.',
        'Serviços acima dos limites do pacote exigem diagnóstico e proposta específica.',
    ],
    'not_included' => [
        'Servidor físico',
        'Storage',
        'Discos',
        'SSDs',
        'Nobreaks',
        'Roteadores',
        'Firewalls',
        'Switches',
        'Licenças Microsoft',
        'Windows Server',
        'CALs de acesso',
        'Antivirus pago',
        'Serviços de nuvem',
        'Mensalidades de provedores externos',
        'Links de internet',
        'Equipamentos de backup',
        'Cabeamento',
        'Infraestrutura eletrica',
        'Suporte fora do escopo mensal contratado',
    ],
];
